/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.UserCart;
import Classes.UserCartDB;
import CustomizedClasses.GlassPanePopup;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Aesthetics
 */
public class AddCart extends javax.swing.JPanel {

    int days;
    double rent = 00;
    UserCart addedbook;
    UserCartDB ucdb;
    BookExpand bookexpand;
    Home home;

    public Home getHome() {
        return home;
    }

    public void setHome(Home home) {
        this.home = home;
    }

    public BookExpand getBookexpand() {
        return bookexpand;
    }

    public void setBookexpand(BookExpand bookexpand) {
        this.bookexpand = bookexpand;
    }

    public void setAddedbook(UserCart addedbook) {
        this.addedbook = addedbook;
    }

    /**
     * Creates new form AddCart
     */
    public AddCart(UserCart usercart) {
        initComponents();
        AddCart.this.addedbook = usercart;
        ucdb = new UserCartDB();
        setOpaque(false);
        jSlider.setValue(1);
        days = jSlider.getValue();
        jDays.setText(String.valueOf(jSlider.getValue()) + " Days");
        rent = days * addedbook.getBook().getPrice();
        jAmount.setText("Php " + String.valueOf(rent) + "0");
        ImageIcon icon = (ImageIcon) jcloseAdd.getIcon();
        Image originalImage = icon.getImage();
        int newWidth = 15;
        int newHeight = 15;
        Image scaledImage = originalImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        jcloseAdd.setIcon(scaledIcon);
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jSlider = new javax.swing.JSlider();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jAmount = new javax.swing.JTextField();
        jDays = new javax.swing.JTextField();
        jcloseAdd = new javax.swing.JButton();
        button1 = new CustomizedClasses.RoundedBorderButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Poppins", 1, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(42, 42, 42));
        jLabel13.setText("Rental Days");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 290, 30));

        jSlider.setBackground(new java.awt.Color(245, 245, 245));
        jSlider.setMajorTickSpacing(3);
        jSlider.setMaximum(30);
        jSlider.setMinimum(1);
        jSlider.setMinorTickSpacing(1);
        jSlider.setSnapToTicks(true);
        jSlider.setToolTipText("");
        jSlider.setValue(1);
        jSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderMouseDragged(evt);
            }
        });
        add(jSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 410, 60));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel15.setText("Days to rent");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 210, 130, 40));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel16.setText("Total Amount");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 262, 190, 40));

        jAmount.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jAmount.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jAmount.setBorder(null);
        add(jAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 140, 40));

        jDays.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jDays.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jDays.setBorder(null);
        jDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDaysActionPerformed(evt);
            }
        });
        add(jDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 140, 40));

        jcloseAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/close.png"))); // NOI18N
        jcloseAdd.setBorder(null);
        jcloseAdd.setBorderPainted(false);
        jcloseAdd.setContentAreaFilled(false);
        jcloseAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcloseAddActionPerformed(evt);
            }
        });
        add(jcloseAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 40, 40));

        button1.setBackground(new java.awt.Color(0, 156, 220));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/cart-white.png"))); // NOI18N
        button1.setText("Add to Cart");
        button1.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 420, 60));

        jScrollPane1.setBorder(null);

        jTextPane1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextPane1.setText("How many days would you like to rent it?");
        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 340, 30));

        jLabel12.setToolTipText("");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderMouseDragged
        // TODO add your handling code here:
        days = jSlider.getValue();
        jDays.setText(String.valueOf(days) + " Days");
        rent = days * addedbook.getBook().getPrice();
        jAmount.setText("Php " + String.valueOf(rent) + "0");
    }//GEN-LAST:event_jSliderMouseDragged

    private void jDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDaysActionPerformed

    private void jcloseAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcloseAddActionPerformed
        // TODO add your handling code here:
        if (bookexpand != null) {
            bookexpand.showNotif();
        }
        if (home != null) {
            home.showNotif();
        }
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_jcloseAddActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:

        if (!(rent == 0 && days == 0)) {
            addedbook.setAmount(rent);
            addedbook.setQuantity(1);
            addedbook.setRentedDays(days);
            ucdb.addCartBook(addedbook);
            addedbook = new UserCart();

            if (bookexpand != null) {
                bookexpand.showNotif();
            }
            if (home != null) {
                home.showNotif();
            }
            jSlider.setValue(0);
            jDays.setText("");
            jAmount.setText("");
            GlassPanePopup.closePopupLast();
        } else {
            JOptionPane.showMessageDialog(null, "Please enter number of days to rent to proceed.", "No Value Found", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomizedClasses.RoundedBorderButton button1;
    private javax.swing.JTextField jAmount;
    private javax.swing.JTextField jDays;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton jcloseAdd;
    // End of variables declaration//GEN-END:variables
}
