/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Book;
import CustomizedClasses.GlassPanePopup;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import static javax.swing.SwingConstants.CENTER;
import static javax.swing.SwingConstants.LEFT;

/**
 *
 * @author Aesthetics
 */
public class BookChoosen extends javax.swing.JPanel {

    /**
     * Creates new form BookChoosen
     *
     * @param year
     */
    private ActionListener act,est,bst;

    BookExpand bookexpand;

    public void setBookexpand(BookExpand bookexpand) {
        this.bookexpand = bookexpand;
    }

    public void setAct(ActionListener act) {
        if (act != null) {
            this.act = act;
        }
    }

    public void setEst(ActionListener est) {
        if (est != null) {
            this.est = est;
        }
    }
        public void setbst(ActionListener bst) {
        if (bst != null) {
            this.bst = bst;
        }
    }
    String addfave = "../img/images/faveadd.png";
    String removefave = "../img/images/faveremove.png";
    private boolean faveStatus;
    Book book;

    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    public boolean isFaveStatus() {
        return faveStatus;
    }

    public void setFaveStatus(boolean faveStatus) {
        this.faveStatus = faveStatus;
        if (!this.faveStatus) {
            favebutton.setBackground(new Color(255, 255, 255));
            favebutton.setForeground(new Color(75, 75, 75));
            favebutton.setText("Add to Favorites");
            fave = createImageIcon(addfave);
        } else {
            favebutton.setBackground(new Color(254, 156, 45));
            favebutton.setForeground(new Color(255, 255, 255));
            favebutton.setText("Remove from Favorites");
            fave = createImageIcon(removefave);
        }
        favebutton.setIcon(fave);
    }

    ImageIcon fave, add;

    public BookChoosen(Book book) {
        initComponents();
        this.book = book;
        this.faveStatus = book.isFaveStatus();
        image.setHorizontalAlignment(CENTER);
        ImageIcon icon = book.getImage();
        Image originalImage = icon.getImage();
        int newWidth = 130;
        int newHeight = 240;
        Image scaledImage = originalImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        image.setIcon(scaledIcon);

        String bookRate = "../img/images/" + book.getRate() + ".png";
        rate.setIcon(createImageIcon(bookRate));

        pubYear.setText("Published Year: " + book.getPublicationDate());
        pubYear.setHorizontalAlignment(LEFT);
        pubYear.setHorizontalTextPosition(LEFT);
        isbn.setText("ISBN: " + book.getIsbn());
        isbn.setHorizontalAlignment(LEFT);
        isbn.setHorizontalTextPosition(LEFT);
        title.setText(book.getTitle());
        author.setText(book.getAuthorFirstName() + " " + book.getAuthorLastName());
        id.setText("#" + book.getBookID());

        if (book.getInventory() != 0) {
            addtocart.setBackground(new Color(0, 156, 220));
        } else {
            addtocart.setBackground(new Color(0, 156, 220));
        }

        if (!this.faveStatus) {
            favebutton.setBackground(new Color(255, 255, 255));
            favebutton.setForeground(new Color(75, 75, 75));
            favebutton.setText("Add to Favorites");
            fave = createImageIcon(addfave);
        } else {
            favebutton.setBackground(new Color(254, 156, 45));
            favebutton.setForeground(new Color(255, 255, 255));
            favebutton.setText("Remove from Favorites");
            fave = createImageIcon(removefave);
        }
        favebutton.setIcon(fave);
        this.setSize(new Dimension(860, 360));
        this.setMaximumSize(new Dimension(860, 360));
        this.setPreferredSize(new Dimension(860, 360));
        this.setMinimumSize(new Dimension(860, 360));
    }

    protected ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = this.getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        by = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        pubYear = new javax.swing.JLabel();
        isbn = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        addtocart = new CustomizedClasses.RoundedBorderButton();
        favebutton = new CustomizedClasses.RoundedBorderButton();
        back = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 252, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 170, 220));

        title.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(42, 42, 42));
        title.setText("Holly");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 510, 40));

        by.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        by.setText("by");
        add(by, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 40, 20));

        author.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        author.setForeground(new java.awt.Color(0, 156, 220));
        author.setText("Stephen King");
        add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 170, 20));
        add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 120, 30));

        status.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        status.setForeground(new java.awt.Color(17, 167, 70));
        status.setText("Available");
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 90, 20));

        pubYear.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pubYear.setText("Published Year:");
        pubYear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(pubYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 170, 20));

        isbn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        isbn.setText("ISBN");
        isbn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 170, 20));

        id.setText("#");
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 90, 20));

        addtocart.setBackground(new java.awt.Color(0, 156, 220));
        addtocart.setForeground(new java.awt.Color(255, 255, 255));
        addtocart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/cart-white.png"))); // NOI18N
        addtocart.setText("Add to Cart");
        addtocart.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        addtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartActionPerformed(evt);
            }
        });
        add(addtocart, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 210, 50));

        favebutton.setForeground(new java.awt.Color(75, 75, 75));
        favebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/book.png"))); // NOI18N
        favebutton.setText("Add to Favorites");
        favebutton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        favebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favebuttonActionPerformed(evt);
            }
        });
        add(favebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 210, 50));

        back.setBackground(new java.awt.Color(159, 159, 159));
        back.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(52, 52, 52));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/backsmall.png"))); // NOI18N
        back.setToolTipText("");
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/bookbg.png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 850, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (bst != null) {
            bst.actionPerformed(null);
        }
        // TODO add your handling code here:

    }

    private void favebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favebuttonActionPerformed
        // TODO add your handling code here:
        if (est != null) {
            est.actionPerformed(null);
        }
    }//GEN-LAST:event_favebuttonActionPerformed

    private void addtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartActionPerformed
        // TODO add your handling code here:
        if (act != null) {
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_addtocartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomizedClasses.RoundedBorderButton addtocart;
    private javax.swing.JLabel author;
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel by;
    private CustomizedClasses.RoundedBorderButton favebutton;
    private javax.swing.JLabel id;
    private javax.swing.JLabel image;
    private javax.swing.JLabel isbn;
    private javax.swing.JLabel pubYear;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel status;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
