/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Book;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import static javax.swing.SwingConstants.CENTER;

/**
 *
 * @author Aesthetics
 */
public class BookPanel extends javax.swing.JPanel implements ActionListener {

    private String bookID;
    private boolean faveStatus;
    private ActionListener act;
    private ActionListener est;

    public String getBookID() {
        return bookID;
    }

    public void setBookID(String bookID) {
        this.bookID = bookID;
    }

    public void setAct(ActionListener act) {
        if (act != null) {
            this.act = act;
        }
    }

    public void setEst(ActionListener est) {
        if (est != null) {
            this.est = est;
        }
    }

    String bgFilePath = "../img/images/box.png";

    public boolean isFaveStatus() {
        return faveStatus;
    }

    public void setFaveStatus(boolean faveStatus) {
        this.faveStatus = faveStatus;
    }

    public BookPanel(Book book) {

        initComponents();
        setProperties();

        image.setIcon(book.getImage());
        bookName.setText(book.getTitle());
        name.setText(book.getAuthorFirstName() + " " + book.getAuthorLastName());
        year.setText(book.getPublicationDate());
        if (book.getInventory() != 0) {
            status.setText("Available");
        } else {
            status.setText("Rented");
        }

        String bookRate = "../img/images/" + book.getRate() + ".png";
        rate.setIcon(createImageIcon(bookRate));
        ID.setText(String.valueOf(book.getBookID()));

        if (book.getInventory() != 0) {
            addButton.setEnabled(true);
            addButton.setBackground(new Color(0, 156, 220));
        } else {
            addButton.setEnabled(false);
            addButton.setBackground(new Color(75, 75, 75));
        }

    }

    public void setProperties() {
        lbackground.setIcon(createImageIcon(bgFilePath));
        lbackground.setSize(new Dimension(200, 330));
        image.setHorizontalAlignment(CENTER);
        image.setHorizontalTextPosition(CENTER);
        status.setHorizontalAlignment(CENTER);
        status.setHorizontalTextPosition(CENTER);
    }

    protected ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = this.getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.out.println("Couldn't find file: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JLabel();
        bookName = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        publicationyear = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        addButton = new CustomizedClasses.RoundedBorderButton();
        image = new javax.swing.JLabel();
        lbackground = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 252, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 10));

        bookName.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        add(bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 30));

        author.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        author.setText("Author: ");
        add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        name.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, 20));

        rate.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 20));

        publicationyear.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        publicationyear.setText("Published Year:");
        add(publicationyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 20));

        year.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 70, 20));

        status.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 60, 20));

        addButton.setBackground(new java.awt.Color(0, 156, 220));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/cart-white.png"))); // NOI18N
        addButton.setText("Add to Cart");
        addButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, 40));

        image.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 140));

        lbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/box.png"))); // NOI18N
        lbackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbackgroundMousePressed(evt);
            }
        });
        add(lbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 210, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void lbackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbackgroundMousePressed
        // TODO add your handling code here:
        if (est != null) {
            est.actionPerformed(null);
        }

    }//GEN-LAST:event_lbackgroundMousePressed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if (act != null) {
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private CustomizedClasses.RoundedBorderButton addButton;
    private javax.swing.JLabel author;
    private javax.swing.JLabel bookName;
    private javax.swing.JLabel image;
    private javax.swing.JLabel lbackground;
    private javax.swing.JLabel name;
    private javax.swing.JLabel publicationyear;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel status;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
