/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.UserCart;
import Classes.UserCartDB;
import Classes.UserCartPanels;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author joopb15
 */
public class CartPanel extends javax.swing.JPanel {

    static UserCart cart;
    UserCartDB ucdb;
    private ActionListener act, actadd, actsub, rem;
    /**
     * Creates new form CartPanel
     */
    String checked = "../img/images/checked.png";
    String unchecked = "../img/images/unchecked.png";
    boolean status;

    public void setAct(ActionListener act) {
        if (act != null) {
            this.act = act;
        }
    }

    public void setRem(ActionListener rem) {
        if (rem != null) {
            this.rem = rem;
        }
    }

    public void setAdd(ActionListener actadd) {
        if (actadd != null) {
            this.actadd = actadd;
        }
    }

    public void setSub(ActionListener actsub) {
        if (actsub != null) {
            this.actsub = actsub;
        }
    }

    public void setChecked() {
        checkbox.setSelected(true);
        checkbox.setIcon(createImageIcon(checked));
        this.setBackground(new Color(246, 252, 255));
    }

    public void setUnchecked() {
        checkbox.setSelected(false);
        checkbox.setIcon(createImageIcon(unchecked));
            this.setBackground(new Color(255, 255, 255));
    }
    public boolean isCheck() {
        return checkbox.isSelected();
    }

//    public void isCheckBoxSelected() {
//        if (checkbox.isSelected()) {
//            checkbox.setIcon(createImageIcon(checked));
//            this.setBackground(new Color(246, 252, 255));
//        } else {
//            checkbox.setIcon(createImageIcon(unchecked));
//            this.setBackground(new Color(255, 255, 255));
//        }
//    }


    public CartPanel(UserCartPanels usercart) {
        initComponents();
        ucdb = new UserCartDB();
        CartPanel.cart = usercart;
        ImageIcon icon = usercart.getBook().getImage();
        Image original = icon.getImage();
        int newWidth = 80;
        int newHeight = 100;
        Image scaledImage = original.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        image.setIcon(scaledIcon);

        title.setText(usercart.getBook().getTitle());
        author.setText("by " + usercart.getBook().getAuthorFirstName() + " " + usercart.getBook().getAuthorLastName());
        date.setText(usercart.getBook().getPublicationDate());
        days.setText(Integer.toString(usercart.getRentedDays()));
        price.setText(Float.toString(usercart.getBook().getPrice()) + "0");
        total.setText(Double.toString(usercart.getAmount()) + "0");

    }

    protected ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = this.getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox = new javax.swing.JCheckBox();
        image = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        remove = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        minus = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        days = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1200, 155));
        setPreferredSize(new java.awt.Dimension(1200, 155));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/unchecked.png"))); // NOI18N
        checkbox.setMaximumSize(new java.awt.Dimension(50, 50));
        checkbox.setMinimumSize(new java.awt.Dimension(50, 50));
        checkbox.setPreferredSize(new java.awt.Dimension(50, 50));
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 90));

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 80, 100));

        date.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        date.setText("2018");
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 310, -1));

        title.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("It Ends with Us");
        title.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 300, 50));

        author.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        author.setText("by Colleen Hoover");
        add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 300, 30));

        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/remove.png"))); // NOI18N
        remove.setBorderPainted(false);
        remove.setContentAreaFilled(false);
        remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 60, 60));

        total.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        total.setText("P240.00");
        add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 0, -1, 160));

        price.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        price.setText("P20.00");
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 0, -1, 160));

        minus.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/buttonsub.png"))); // NOI18N
        minus.setBorderPainted(false);
        minus.setContentAreaFilled(false);
        minus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 40, 40));

        add.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/buttonadd.png"))); // NOI18N
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 40, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/checkoutnav.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 150, 1250, 70));

        days.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        days.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        days.setText("2");
        days.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true));
        add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        // TODO add your handling code here:
        if (act != null) {
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_checkboxActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        if (rem != null) {

            rem.actionPerformed(null);

        }
    }//GEN-LAST:event_removeActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        if (actsub != null) {
            actsub.actionPerformed(null);
        }
    }//GEN-LAST:event_minusActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if (actadd != null) {
            actadd.actionPerformed(null);
        }
    }//GEN-LAST:event_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel author;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel date;
    private javax.swing.JTextField days;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton minus;
    private javax.swing.JLabel price;
    private javax.swing.JButton remove;
    private javax.swing.JLabel title;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
