/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import Classes.RentalDB;
import Classes.UserCartDB;
import Classes.UserCartPanels;
import Classes.UserSession;
import CustomizedClasses.GlassPanePopup;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import static javax.swing.SwingConstants.CENTER;

/**
 *
 * @author joopb15
 */
public class Cart extends javax.swing.JFrame {

    private HashMap<String, UserCartPanels> selected = new HashMap<>();
    int booksize;
    double amount;

    public void addSelected(UserCartPanels uc) {
        this.selected.put(uc.getBook().getBookID(), uc);
    }

    public void removeSelected(UserCartPanels uc) {
        this.selected.remove(uc.getBook().getBookID());
    }

    public void removeAllSelected() {
        this.selected.clear();
    }

    public HashMap<String, UserCartPanels> getSelected() {
        return selected;
    }

    public void setSelected(HashMap<String, UserCartPanels> selected) {
        this.selected = selected;
    }

    public void updateSelected(UserCartPanels uc) {
        this.selected.replace(uc.getBook().getBookID(), uc);
    }

    int dropdowncounter = 0;
    static ArrayList<UserCartPanels> usercartpanels = new ArrayList<>();
    UserCartDB ucdb;
    RentalDB rdb;

//    private ArrayList<UserCartPanels> usercartpanels;
    public Cart() {
        initComponents();
        ucdb = new UserCartDB();
        rdb = new RentalDB();
        execute();
        GlassPanePopup.install(Cart.this);

    }

    public void execute() {
        jtotalitems.setText(Integer.toString(ucdb.countUserCart(UserSession.getInstance().getUser().getUserID())) + " Items");
        usercartpanels = ucdb.getAllCartBook(Cart.this, UserSession.getInstance().getUser().getUserID());
        if (!selected.isEmpty()) {
            booksize = selected.size();
            amount = getTotalAmount(selected);
        } else {
            booksize = 0;
            amount = 0;
        }
        numofbooks.setText(Integer.toString(booksize) + " Books");
        totalamount.setText(Double.toString(amount) + "0");
        showNotif();
        int num = loadBooks(jCartPanel, usercartpanels);
        setPanelHeight(num);

    }

    public double getTotalAmount(HashMap<String, UserCartPanels> selected) {
        double amount = 0;
        for (UserCartPanels uc : selected.values()) {
            amount += uc.getAmount();
        }
        return amount;
    }

    public void setPanelHeight(int num) {
        jCartPanel.setPreferredSize(new Dimension(1200, calculatePanelHeight(num)));
        jCartPanel.setSize(new Dimension(1200, calculatePanelHeight(num)));
        jCartPanel.setMinimumSize(new Dimension(1200, calculatePanelHeight(num)));
        jCartPanel.setMaximumSize(new Dimension(1200, calculatePanelHeight(num)));

        cartbody.setPreferredSize(new Dimension(1200, calculatePanelHeight(num) + 130));
        cartbody.setSize(new Dimension(1200, calculatePanelHeight(num) + 130));
        cartbody.setMinimumSize(new Dimension(1200, calculatePanelHeight(num) + 130));
        cartbody.setMaximumSize(new Dimension(1200, calculatePanelHeight(num) + 130));
        jScrollPane1.setViewportView(cartbody);
        jScrollPane1.setScrollSpeed(5);
    }

    public int loadBooks(Container container, ArrayList<UserCartPanels> p) {
        int count = 0;
        container.removeAll();
        for (UserCartPanels ucp : p) {
            setCheck(selected, ucp);
            container.add(ucp.getCartpanel());
            count++;
        }
        return count;
    }

    public void setCheck(HashMap<String, UserCartPanels> selected, UserCartPanels ucp) {
        CartPanel cartPanel = ucp.getCartpanel();
        UserCartPanels selectedUCP = selected.get(ucp.getBook().getBookID());
        if (selectedUCP != null) {
            cartPanel.setChecked();
        } else {
            cartPanel.setUnchecked();
        }
    }

    public int calculatePanelHeight(int numBooks) {
        int height = numBooks * 155;
        return height;
    }

    public void showNotif() {
        notiflabel.setText(String.valueOf(ucdb.countUserCart(UserSession.getInstance().getUser().getUserID())));
        notiflabel.setHorizontalTextPosition(CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayeredPanel = new javax.swing.JPanel();
        Main = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        notiflabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLibrary = new javax.swing.JButton();
        jTransaction = new javax.swing.JButton();
        jCart = new javax.swing.JButton();
        jSideMenu = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jDropdown = new javax.swing.JPanel();
        jLogout = new javax.swing.JButton();
        jProfile = new javax.swing.JButton();
        bottomnav = new javax.swing.JPanel();
        numofbooks = new javax.swing.JLabel();
        jTotalAmount = new javax.swing.JLabel();
        totalamount = new javax.swing.JLabel();
        jselectedbooks = new javax.swing.JLabel();
        button1 = new CustomizedClasses.RoundedBorderButton();
        jnavbg = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        cart = new javax.swing.JPanel();
        jScrollPane1 = new CustomizedClasses.ScrollPaneWin11();
        cartbody = new javax.swing.JPanel();
        jtotalitems = new javax.swing.JLabel();
        jtotal = new javax.swing.JLabel();
        jbookcart = new javax.swing.JLabel();
        jproductdetails = new javax.swing.JLabel();
        jremove = new javax.swing.JLabel();
        jprice = new javax.swing.JLabel();
        jdays = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCartPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LayeredPanel.setBackground(new java.awt.Color(255, 255, 255));
        LayeredPanel.setMaximumSize(new java.awt.Dimension(1200, 790));
        LayeredPanel.setLayout(new java.awt.CardLayout());

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setMaximumSize(new java.awt.Dimension(1200, 790));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notiflabel.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        notiflabel.setForeground(new java.awt.Color(255, 255, 255));
        notiflabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notiflabel.setText("1");
        notiflabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        notiflabel.setIconTextGap(0);
        Header.add(notiflabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 18, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/cartnotif.png"))); // NOI18N
        Header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 17, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/homelogo.png"))); // NOI18N
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 160, 90));

        jLibrary.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLibrary.setForeground(new java.awt.Color(30, 30, 30));
        jLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/lib-unactive.png"))); // NOI18N
        jLibrary.setText("Library");
        jLibrary.setContentAreaFilled(false);
        jLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLibraryActionPerformed(evt);
            }
        });
        Header.add(jLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 170, 90));

        jTransaction.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jTransaction.setForeground(new java.awt.Color(30, 30, 30));
        jTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/transact-unactive.png"))); // NOI18N
        jTransaction.setText("Transactions");
        jTransaction.setContentAreaFilled(false);
        jTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTransactionActionPerformed(evt);
            }
        });
        Header.add(jTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 210, 90));

        jCart.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jCart.setForeground(new java.awt.Color(254, 156, 44));
        jCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/cart-active.png"))); // NOI18N
        jCart.setText("Cart");
        jCart.setContentAreaFilled(false);
        jCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCartActionPerformed(evt);
            }
        });
        Header.add(jCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 120, 90));

        jSideMenu.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jSideMenu.setForeground(new java.awt.Color(146, 146, 146));
        jSideMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/sidemenu.png"))); // NOI18N
        jSideMenu.setContentAreaFilled(false);
        jSideMenu.setIconTextGap(10);
        jSideMenu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSideMenuFocusLost(evt);
            }
        });
        jSideMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSideMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSideMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSideMenuMousePressed(evt);
            }
        });
        jSideMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSideMenuActionPerformed(evt);
            }
        });
        Header.add(jSideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 150, 90));
        Header.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1210, 100));

        Main.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jDropdown.setBackground(new java.awt.Color(255, 255, 255));
        jDropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDropdownMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jDropdownMouseExited(evt);
            }
        });
        jDropdown.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLogout.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLogout.setForeground(new java.awt.Color(72, 72, 72));
        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/logout.png"))); // NOI18N
        jLogout.setText("Logout");
        jLogout.setContentAreaFilled(false);
        jLogout.setFocusPainted(false);
        jLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLogout.setIconTextGap(10);
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLogoutMousePressed(evt);
            }
        });
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        jDropdown.add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 50));

        jProfile.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jProfile.setForeground(new java.awt.Color(72, 72, 72));
        jProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/profile.png"))); // NOI18N
        jProfile.setText("Profile");
        jProfile.setContentAreaFilled(false);
        jProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jProfile.setIconTextGap(13);
        jProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProfileActionPerformed(evt);
            }
        });
        jDropdown.add(jProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 50));

        Main.add(jDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 170, 0));

        bottomnav.setBackground(new java.awt.Color(255, 255, 255));
        bottomnav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numofbooks.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        numofbooks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        numofbooks.setText("3 Books");
        bottomnav.add(numofbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 100, 90));

        jTotalAmount.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTotalAmount.setText("Total Amount");
        bottomnav.add(jTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 100, 90));

        totalamount.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        totalamount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalamount.setText("P1200.00");
        bottomnav.add(totalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 100, 90));

        jselectedbooks.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jselectedbooks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jselectedbooks.setText("Selected Books");
        bottomnav.add(jselectedbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 90));

        button1.setBackground(new java.awt.Color(0, 156, 220));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Checkout");
        button1.setToolTipText("");
        button1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        bottomnav.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 25, 170, 40));

        jnavbg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jnavbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/checkoutnav.png"))); // NOI18N
        bottomnav.add(jnavbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        Main.add(bottomnav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1200, -1));

        Body.setBackground(new java.awt.Color(250, 250, 250));
        Body.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 252, 252)));
        Body.setLayout(new java.awt.CardLayout());

        cart.setBackground(new java.awt.Color(255, 255, 255));
        cart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cartbody.setBackground(new java.awt.Color(255, 255, 255));
        cartbody.setPreferredSize(new java.awt.Dimension(1200, 700));
        cartbody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtotalitems.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jtotalitems.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jtotalitems.setText("3 Items");
        cartbody.add(jtotalitems, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, 140, 40));

        jtotal.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jtotal.setForeground(new java.awt.Color(102, 102, 102));
        jtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtotal.setText("Total");
        cartbody.add(jtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(993, 90, 120, 40));

        jbookcart.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jbookcart.setText("Book Cart");
        cartbody.add(jbookcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 200, 40));

        jproductdetails.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jproductdetails.setForeground(new java.awt.Color(102, 102, 102));
        jproductdetails.setText("Product Details");
        cartbody.add(jproductdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, 40));

        jremove.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jremove.setForeground(new java.awt.Color(102, 102, 102));
        jremove.setText("Remove");
        cartbody.add(jremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 70, 40));

        jprice.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jprice.setForeground(new java.awt.Color(102, 102, 102));
        jprice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jprice.setText("Price");
        cartbody.add(jprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(883, 90, 90, 40));

        jdays.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jdays.setForeground(new java.awt.Color(102, 102, 102));
        jdays.setText("Rented Days");
        cartbody.add(jdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 110, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/separator.png"))); // NOI18N
        cartbody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 1060, 10));

        jCartPanel.setBackground(new java.awt.Color(255, 255, 255));
        jCartPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        jCartPanel.setLayout(new javax.swing.BoxLayout(jCartPanel, javax.swing.BoxLayout.PAGE_AXIS));
        cartbody.add(jCartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1200, -1));

        jScrollPane1.setViewportView(cartbody);

        cart.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 580));

        Body.add(cart, "card3");

        Main.add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 1200, 580));

        LayeredPanel.add(Main, "Main");

        getContentPane().add(LayeredPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1216, 798));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLibraryActionPerformed
        // TODO add your handling code here:
        Home myhome = new Home();
        myhome.show();
        dispose();
    }//GEN-LAST:event_jLibraryActionPerformed

    private void jTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTransactionActionPerformed
        // TODO add your handling code here:
        Transactions mytransact = new Transactions();
        mytransact.show();
        dispose();
    }//GEN-LAST:event_jTransactionActionPerformed

    private void jCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCartActionPerformed
        // TODO add your handling code here:
        Cart cartpage = new Cart();
        cartpage.show();
        dispose();
    }//GEN-LAST:event_jCartActionPerformed

    private void jSideMenuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSideMenuFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jSideMenuFocusLost

    private void jSideMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSideMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jSideMenuMouseEntered

    private void jSideMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSideMenuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jSideMenuMouseExited

    private void jSideMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSideMenuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSideMenuMousePressed

    private void jSideMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSideMenuActionPerformed
        // TODO add your handling code here:
        dropdowncounter++;
        if (dropdowncounter % 2 != 0) {
            jDropdown.setSize(160, 130);
        } else {
            jDropdown.setSize(0, 0);
        }
    }//GEN-LAST:event_jSideMenuActionPerformed

    private void jLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogoutMousePressed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        UserSession session = UserSession.getInstance();
        session.clearSession();
        Login mylogin;
        mylogin = new Login();
        mylogin.show();
        dispose();
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProfileActionPerformed

    private void jDropdownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDropdownMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jDropdownMouseEntered

    private void jDropdownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDropdownMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jDropdownMouseExited

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        int max = 3 - rdb.countRentalActive(UserSession.getInstance().getUser().getUserID());
        if (max > 0 && this.booksize <= max) {
            if (!selected.isEmpty()) {
                CheckoutDetails cd = new CheckoutDetails(this.amount, this.booksize);
                cd.setCart(Cart.this);
                GlassPanePopup.showPopup(cd);
            } else {
                GlassPanePopup.showPopup(new NoSelectedBooks());
            }
        } else {
            JOptionPane.showMessageDialog(null, "You have reached the maximum renting of books.", "Maximum Rented", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel LayeredPanel;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel bottomnav;
    private CustomizedClasses.RoundedBorderButton button1;
    private javax.swing.JPanel cart;
    private javax.swing.JPanel cartbody;
    private javax.swing.JButton jCart;
    private javax.swing.JPanel jCartPanel;
    private javax.swing.JPanel jDropdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jLibrary;
    private javax.swing.JButton jLogout;
    private javax.swing.JButton jProfile;
    private CustomizedClasses.ScrollPaneWin11 jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jSideMenu;
    private javax.swing.JLabel jTotalAmount;
    private javax.swing.JButton jTransaction;
    private javax.swing.JLabel jbookcart;
    private javax.swing.JLabel jdays;
    private javax.swing.JLabel jnavbg;
    private javax.swing.JLabel jprice;
    private javax.swing.JLabel jproductdetails;
    private javax.swing.JLabel jremove;
    private javax.swing.JLabel jselectedbooks;
    private javax.swing.JLabel jtotal;
    private javax.swing.JLabel jtotalitems;
    private javax.swing.JLabel notiflabel;
    private javax.swing.JLabel numofbooks;
    private javax.swing.JLabel totalamount;
    // End of variables declaration//GEN-END:variables
}
