/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Checkout;
import CustomizedClasses.GlassPanePopup;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Aesthetics
 */
public class CheckoutHistoryPanel extends javax.swing.JPanel {

    Timestamp date;
    ArrayList<Checkout> checkouts = new ArrayList<>();
    SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy");
    String formattedDate;
    Double totalAmount = 0.00;
    List<String> checkoutID = new ArrayList<>();
    String transactID;
    public CheckoutHistoryPanel(Timestamp date,ArrayList<Checkout> checkout) {
        initComponents();
        this.date = date;
        this.checkouts = checkout;
        formattedDate = dateFormat.format(this.date);
        checkoutDate.setText(formattedDate);
        this.totalBooks.setText(Integer.toString(this.checkouts.size())); 
        this.libraryFee.setText(Double.toString(this.checkouts.get(0).getLibraryFee())+"0");
        for(Checkout ck : checkout){
            totalAmount += ck.getTotalAmount();
        }
        totalAmount += this.checkouts.get(0).getLibraryFee() + this.checkouts.get(0).getDeliveryFee();
        this.amount.setText(Double.toString(totalAmount)+"0");
        if(this.checkouts.get(0).getCheckoutStatus().equals("Failed")){
            this.status.setForeground(new Color(227,17,104));
        }else {
            this.status.setForeground(new Color(21,180,106));
        }
        this.status.setText(this.checkouts.get(0).getCheckoutStatus());
        
        for(Checkout ck: checkout){
            this.checkoutID.add(ck.getCheckoutID());
            this.transactID = ck.getTransactionID();
        }
        if(this.transactID != null){
            this.transactionID.setText(this.transactID);
        }else {
            this.transactionID.setText("N/A");
        }
        
        
    }
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 0, 0));
        g2.dispose();
        super.paintComponents(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bg = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        libraryFee = new javax.swing.JLabel();
        checkoutDate = new javax.swing.JLabel();
        totalBooks = new javax.swing.JLabel();
        transactionID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 80));

        status.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        status.setForeground(new java.awt.Color(21, 180, 106));
        status.setText("Confirmed");
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 100, 80));

        amount.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        amount.setForeground(new java.awt.Color(82, 82, 82));
        amount.setText("Php 25.00");
        add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 90, 80));

        libraryFee.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        libraryFee.setForeground(new java.awt.Color(82, 82, 82));
        libraryFee.setText("Php 192.00");
        add(libraryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 110, 80));

        checkoutDate.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        checkoutDate.setForeground(new java.awt.Color(52, 52, 52));
        checkoutDate.setText("May 23, 2023");
        add(checkoutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 120, 80));

        totalBooks.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        totalBooks.setForeground(new java.awt.Color(82, 82, 82));
        totalBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBooks.setText("1");
        add(totalBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 90, 80));

        transactionID.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        transactionID.setForeground(new java.awt.Color(52, 52, 52));
        transactionID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transactionID.setText("123123");
        add(transactionID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new CheckoutSummary(this.checkoutID,this.transactID));
    }//GEN-LAST:event_bgMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel checkoutDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel libraryFee;
    private javax.swing.JLabel status;
    private javax.swing.JLabel totalBooks;
    private javax.swing.JLabel transactionID;
    // End of variables declaration//GEN-END:variables
}
