/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Book;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;

/**
 *
 * @author Aesthetics
 */
public class CheckoutBooks extends javax.swing.JPanel {

    /**
     * Creates new form CheckoutBooks
     */
    public CheckoutBooks(Book book) {
        initComponents();
        bookID.setText("Book #" + book.getBookID());
        title.setText(book.getTitle());
        author.setText("by " + book.getAuthorFirstName() + " " + book.getAuthorLastName());
        date1.setText(book.getPublicationDate());
        ImageIcon icon = (ImageIcon) book.getImage();
        Image originalImage = icon.getImage();
        int newWidth = 70;
        int newHeight = 90;
        Image scaledImage = originalImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        image.setIcon(scaledIcon);
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        bookID = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setToolTipText("");
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 60, 70));

        author.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        author.setForeground(new java.awt.Color(82, 82, 82));
        author.setText("by Colleen Hoover");
        add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 55, 170, 20));

        bookID.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        bookID.setForeground(new java.awt.Color(82, 82, 82));
        bookID.setText("Book ID  #");
        add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 160, 10));

        date1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(82, 82, 82));
        date1.setText("2018");
        add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 75, 120, 20));

        title.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        title.setText("jLabel1");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 230, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x1");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 50, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/boxsummary.png"))); // NOI18N
        jLabel1.setText("0");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 120));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel bookID;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
