/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Book;
import Classes.BookDB;
import Classes.Rental;
import CustomizedClasses.GlassPanePopup;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;

/**
 *
 * @author Aesthetics
 */
public class CurrentRentedBooks extends javax.swing.JPanel {

    private Rental rental;
    
    
    public Rental getRental() {
        return rental;
    }

    public void setRental(Rental rental) {
        this.rental = rental;
    }
    Executable executable;

    BookDB bdb;
    Book book;
    Timestamp timestamp;
    SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy");
    String formattedDate;
    
    
    public CurrentRentedBooks(Rental rental,Executable executable) {
        initComponents();

        this.executable = executable;
        this.rental = rental;
        bdb = new BookDB();
        book = bdb.getBook(rental.getBookID());
        bookID.setText("Book #" + book.getBookID());
        ImageIcon icon = (ImageIcon) book.getImage();
        Image originalImage = icon.getImage();
        int newWidth = 70;
        int newHeight = 90;
        Image scaledImage = originalImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        image.setIcon(scaledIcon);
        author.setText("by " + book.getAuthorFirstName() + " " + book.getAuthorLastName());
        title.setText(book.getTitle());
        publicationdate.setText(book.getPublicationDate());       
        rentalID.setText(rental.getRentalID());
        
        //settingup dates
        timestamp = rental.getStartDate();
        formattedDate = dateFormat.format(timestamp);
        startDate.setText(formattedDate);
        
        timestamp = rental.getEndDate();
        formattedDate = dateFormat.format(timestamp);
        endDate.setText(formattedDate);
        
        rentStatus.setText(rental.getRentStatus());

    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        bookID = new javax.swing.JLabel();
        publicationdate = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        rentStatus = new javax.swing.JLabel();
        jRentStatus = new javax.swing.JLabel();
        endDate = new javax.swing.JLabel();
        jEndDate = new javax.swing.JLabel();
        startDate = new javax.swing.JLabel();
        jStartDate = new javax.swing.JLabel();
        jRentalID = new javax.swing.JLabel();
        rentalID = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(249, 249, 249));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 120));

        image.setToolTipText("");
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 70, 90));

        bookID.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        bookID.setForeground(new java.awt.Color(82, 82, 82));
        bookID.setText("Book ID  #");
        add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 160, 10));

        publicationdate.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        publicationdate.setForeground(new java.awt.Color(82, 82, 82));
        publicationdate.setText("2018");
        add(publicationdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 75, 130, 20));

        title.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        title.setText("jLabel1");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 35, 140, 20));

        author.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        author.setForeground(new java.awt.Color(82, 82, 82));
        author.setText("by Colleen Hoover");
        add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 55, 130, 20));

        rentStatus.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        rentStatus.setForeground(new java.awt.Color(0, 126, 220));
        rentStatus.setText("Ongoing");
        add(rentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 53, 90, 20));

        jRentStatus.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jRentStatus.setForeground(new java.awt.Color(113, 113, 113));
        jRentStatus.setText("Status");
        add(jRentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 80, 10));

        endDate.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        endDate.setForeground(new java.awt.Color(102, 102, 102));
        endDate.setText("05/11/25");
        add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 53, 120, 20));

        jEndDate.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jEndDate.setForeground(new java.awt.Color(113, 113, 113));
        jEndDate.setText("End Date");
        add(jEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 90, 10));

        startDate.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        startDate.setForeground(new java.awt.Color(102, 102, 102));
        startDate.setText("05/11/25");
        add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 53, 100, 20));

        jStartDate.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jStartDate.setForeground(new java.awt.Color(113, 113, 113));
        jStartDate.setText("Start Date");
        add(jStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 110, 10));

        jRentalID.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jRentalID.setForeground(new java.awt.Color(113, 113, 113));
        jRentalID.setText("Rental ID");
        add(jRentalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 90, 10));

        rentalID.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        rentalID.setForeground(new java.awt.Color(82, 82, 82));
        rentalID.setText("RN00234");
        add(rentalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 53, 110, 20));

        bg.setBackground(new java.awt.Color(252, 252, 252));
        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/crbbg.png"))); // NOI18N
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new CurrentRentedBooksExpand(this.rental,this.executable));
    }//GEN-LAST:event_bgMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new CurrentRentedBooksExpand(this.rental,this.executable));
    }//GEN-LAST:event_jLabel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bookID;
    private javax.swing.JLabel endDate;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jEndDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jRentStatus;
    private javax.swing.JLabel jRentalID;
    private javax.swing.JLabel jStartDate;
    private javax.swing.JLabel publicationdate;
    private javax.swing.JLabel rentStatus;
    private javax.swing.JLabel rentalID;
    private javax.swing.JLabel startDate;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
