/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Book;
import Classes.BookDB;
import Classes.Rental;
import CustomizedClasses.GlassPanePopup;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author Aesthetics
 */
public class CurrentRentedBooksExpand extends javax.swing.JPanel {

    Executable executable;
    BookDB bdb;
    Book book;
    Timestamp timestamp;
    SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy");
    String formattedDate;
    Rental rental;

    public CurrentRentedBooksExpand(Rental rental, Executable executable) {
        initComponents();
        setOpaque(false);
        this.rental = rental;
        this.executable = executable;
        bdb = new BookDB();
        book = bdb.getBook(rental.getBookID());
        bookID.setText("Book #" + book.getBookID());
        isbn.setText(book.getIsbn());
        String bookRate = "../img/images/" + book.getRate() + ".png";
        ratings.setIcon(createImageIcon(bookRate));
        ImageIcon icon = (ImageIcon) book.getImage();
        Image originalImage = icon.getImage();
        int newWidth = 120;
        int newHeight = 140;
        Image scaledImage = originalImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        bookimage.setIcon(scaledIcon);
        author.setText("by " + book.getAuthorFirstName() + " " + book.getAuthorLastName());
        title.setText(book.getTitle());
        pubDate.setText(book.getPublicationDate());
        rentalID.setText(rental.getRentalID());
        checkoutID.setText(rental.getCheckoutID());

        //settingup dates
        timestamp = rental.getStartDate();
        formattedDate = dateFormat.format(timestamp);
        startDate.setText(formattedDate);

        timestamp = rental.getEndDate();
        formattedDate = dateFormat.format(timestamp);
        endDate.setText(formattedDate);

        rentStatus.setText(rental.getRentStatus());
        if (rental.getRentStatus().equals("Returned")) {
            timestamp = rental.getReturnDate();
            if (timestamp != null) { // add null check here
                formattedDate = dateFormat.format(timestamp);
                returnDate.setText(formattedDate);
            }
            returnCondition.setText(rental.getReturnCondition());
            returnBook.setEnabled(false);
            returnBook.setBackground(new Color(206, 206, 206));
        }

    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }
    protected ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = this.getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.out.println("Couldn't find file: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        title2 = new javax.swing.JLabel();
        bookimage = new javax.swing.JLabel();
        BookDetails = new javax.swing.JLabel();
        jBookID = new javax.swing.JLabel();
        jBookTitle = new javax.swing.JLabel();
        jPublicationDate = new javax.swing.JLabel();
        bookID = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        pubDate = new javax.swing.JLabel();
        jisbn = new javax.swing.JLabel();
        isbn = new javax.swing.JLabel();
        rentalID = new javax.swing.JLabel();
        jRentalID = new javax.swing.JLabel();
        checkoutID = new javax.swing.JLabel();
        jCheckoutID = new javax.swing.JLabel();
        RentalDetails = new javax.swing.JLabel();
        jStartDate = new javax.swing.JLabel();
        startDate = new javax.swing.JLabel();
        endDate = new javax.swing.JLabel();
        jEndDate = new javax.swing.JLabel();
        rentStatus = new javax.swing.JLabel();
        jRentStatus = new javax.swing.JLabel();
        returnDate = new javax.swing.JLabel();
        jReturnDate = new javax.swing.JLabel();
        returnCondition = new javax.swing.JLabel();
        jReturnCondition = new javax.swing.JLabel();
        returnBook = new CustomizedClasses.RoundedBorderButton();
        jRatings = new javax.swing.JLabel();
        ratings = new javax.swing.JLabel();
        Summary = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        jBookAuthor = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/backsmall.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, 40));

        title2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(0, 156, 220));
        title2.setText("Rental");
        add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 80, 40));

        bookimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(bookimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, 170));

        BookDetails.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        BookDetails.setForeground(new java.awt.Color(32, 32, 32));
        BookDetails.setText("Book Details");
        add(BookDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 230, 20));

        jBookID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jBookID.setForeground(new java.awt.Color(105, 105, 105));
        jBookID.setText("Book ID");
        add(jBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 105, 150, 20));

        jBookTitle.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jBookTitle.setForeground(new java.awt.Color(105, 105, 105));
        jBookTitle.setText("Book Title");
        add(jBookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, 20));

        jPublicationDate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPublicationDate.setForeground(new java.awt.Color(105, 105, 105));
        jPublicationDate.setText("Publication Date");
        add(jPublicationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, 20));

        bookID.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bookID.setForeground(new java.awt.Color(52, 52, 52));
        bookID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bookID.setText("Pickup");
        add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 105, 210, 20));

        title.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        title.setForeground(new java.awt.Color(82, 82, 82));
        title.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        title.setText("Location");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 210, 20));

        pubDate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        pubDate.setForeground(new java.awt.Color(82, 82, 82));
        pubDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pubDate.setText("Landmark:");
        add(pubDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 210, 20));

        jisbn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jisbn.setForeground(new java.awt.Color(105, 105, 105));
        jisbn.setText("ISBN");
        add(jisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 205, 150, 20));

        isbn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        isbn.setForeground(new java.awt.Color(82, 82, 82));
        isbn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        isbn.setText("ISBN");
        add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 205, 210, 20));

        rentalID.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        rentalID.setForeground(new java.awt.Color(52, 52, 52));
        rentalID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rentalID.setText("Rental ID");
        add(rentalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 302, 150, 20));

        jRentalID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRentalID.setForeground(new java.awt.Color(105, 105, 105));
        jRentalID.setText("Rental ID");
        add(jRentalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 302, 150, 20));

        checkoutID.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        checkoutID.setForeground(new java.awt.Color(52, 52, 52));
        checkoutID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        checkoutID.setText("Checkout ID");
        add(checkoutID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 150, 20));

        jCheckoutID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jCheckoutID.setForeground(new java.awt.Color(105, 105, 105));
        jCheckoutID.setText("Checkout ID");
        add(jCheckoutID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 150, 20));

        RentalDetails.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        RentalDetails.setForeground(new java.awt.Color(32, 32, 32));
        RentalDetails.setText("Rental Details");
        add(RentalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 230, 30));

        jStartDate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jStartDate.setForeground(new java.awt.Color(105, 105, 105));
        jStartDate.setText("Start Date");
        add(jStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 150, -1));

        startDate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        startDate.setForeground(new java.awt.Color(82, 82, 82));
        startDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        startDate.setText("Start Date");
        add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 150, -1));

        endDate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        endDate.setForeground(new java.awt.Color(82, 82, 82));
        endDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        endDate.setText("End Date");
        add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 150, -1));

        jEndDate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jEndDate.setForeground(new java.awt.Color(105, 105, 105));
        jEndDate.setText("End Date");
        add(jEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 145, -1));

        rentStatus.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        rentStatus.setForeground(new java.awt.Color(39, 171, 65));
        rentStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rentStatus.setText("Return Status");
        add(rentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 150, -1));

        jRentStatus.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRentStatus.setForeground(new java.awt.Color(105, 105, 105));
        jRentStatus.setText("Rent Status");
        add(jRentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 150, -1));

        returnDate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        returnDate.setForeground(new java.awt.Color(82, 82, 82));
        returnDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        returnDate.setText("---");
        add(returnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 445, 150, -1));

        jReturnDate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jReturnDate.setForeground(new java.awt.Color(105, 105, 105));
        jReturnDate.setText("Return Date");
        add(jReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 445, 150, -1));

        returnCondition.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        returnCondition.setForeground(new java.awt.Color(82, 82, 82));
        returnCondition.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        returnCondition.setText("---");
        add(returnCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 150, 20));

        jReturnCondition.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jReturnCondition.setForeground(new java.awt.Color(105, 105, 105));
        jReturnCondition.setText("Return Condition");
        add(jReturnCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 150, 20));

        returnBook.setBackground(new java.awt.Color(0, 156, 220));
        returnBook.setForeground(new java.awt.Color(255, 255, 255));
        returnBook.setText("Return Book");
        returnBook.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookActionPerformed(evt);
            }
        });
        add(returnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 510, 60));

        jRatings.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRatings.setForeground(new java.awt.Color(105, 105, 105));
        jRatings.setText("Ratings");
        add(jRatings, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 225, 150, 30));

        ratings.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ratings.setForeground(new java.awt.Color(104, 104, 104));
        ratings.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ratings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/4.0.png"))); // NOI18N
        add(ratings, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 225, 210, 30));

        Summary.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        Summary.setText("Summary");
        add(Summary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 130, 40));

        author.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        author.setForeground(new java.awt.Color(82, 82, 82));
        author.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        author.setText("Location");
        add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 155, 210, 20));

        jBookAuthor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jBookAuthor.setForeground(new java.awt.Color(105, 105, 105));
        jBookAuthor.setText("Book Author");
        add(jBookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 155, 150, 20));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookActionPerformed
        // TODO add your handling code here:

        GlassPanePopup.showPopup(new ReturnBook(this.rental, this.executable));
    }//GEN-LAST:event_returnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookDetails;
    private javax.swing.JLabel RentalDetails;
    private javax.swing.JLabel Summary;
    private javax.swing.JLabel author;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bookID;
    private javax.swing.JLabel bookimage;
    private javax.swing.JLabel checkoutID;
    private javax.swing.JLabel endDate;
    private javax.swing.JLabel isbn;
    private javax.swing.JLabel jBookAuthor;
    private javax.swing.JLabel jBookID;
    private javax.swing.JLabel jBookTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCheckoutID;
    private javax.swing.JLabel jEndDate;
    private javax.swing.JLabel jPublicationDate;
    private javax.swing.JLabel jRatings;
    private javax.swing.JLabel jRentStatus;
    private javax.swing.JLabel jRentalID;
    private javax.swing.JLabel jReturnCondition;
    private javax.swing.JLabel jReturnDate;
    private javax.swing.JLabel jStartDate;
    private javax.swing.JLabel jisbn;
    private javax.swing.JLabel pubDate;
    private javax.swing.JLabel ratings;
    private javax.swing.JLabel rentStatus;
    private javax.swing.JLabel rentalID;
    private CustomizedClasses.RoundedBorderButton returnBook;
    private javax.swing.JLabel returnCondition;
    private javax.swing.JLabel returnDate;
    private javax.swing.JLabel startDate;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
