/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import CustomizedClasses.GlassPanePopup;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Aesthetics
 */
public class ErrorCheckout extends javax.swing.JPanel {

    /**
     * Creates new form ErrorAddress
     */
    public ErrorCheckout() {
        initComponents();
    }
    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        g2.dispose();
        super.paintComponent(grphcs);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        noted = new CustomizedClasses.RoundedBorderButton();
        bg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(42, 42, 42));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Checkout Error");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 430, 30));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Make sure to select delivery method and address,");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 30));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("and payment method before checking out.");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 430, 60));

        noted.setBackground(new java.awt.Color(227, 17, 104));
        noted.setForeground(new java.awt.Color(255, 255, 255));
        noted.setText("Let me try again");
        noted.setFocusable(false);
        noted.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        noted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notedActionPerformed(evt);
            }
        });
        add(noted, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 370, 50));
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void notedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notedActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_notedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private CustomizedClasses.RoundedBorderButton noted;
    // End of variables declaration//GEN-END:variables
}
