/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.FavoriteDB;
import Classes.UserSession;
import CustomizedClasses.GlassPanePopup;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Aesthetics
 */
public class FavoriteAdd extends javax.swing.JPanel {
    FavoriteDB fdb;
    BookExpand bookexpand;
    /**
     * Creates new form AddFavorite
     */
    public FavoriteAdd(BookExpand bookexpand) {
        initComponents();
        fdb = new FavoriteDB();
        this.bookexpand = bookexpand;
    }
    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcloseAdd1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        add = new CustomizedClasses.RoundedBorderButton();
        cancel = new CustomizedClasses.RoundedBorderButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcloseAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/close.png"))); // NOI18N
        jcloseAdd1.setBorder(null);
        jcloseAdd1.setBorderPainted(false);
        jcloseAdd1.setContentAreaFilled(false);
        jcloseAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcloseAdd1ActionPerformed(evt);
            }
        });
        add(jcloseAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 40, 40));

        jLabel17.setFont(new java.awt.Font("Poppins", 1, 32)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(42, 42, 42));
        jLabel17.setText("Add to Favorites");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 290, 30));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setText("You are about to add this book to your favorites.");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 400, 30));

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel22.setText("Choose to proceed.");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 400, 40));

        add.setBackground(new java.awt.Color(0, 156, 220));
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.setFocusable(false);
        add.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 120, 50));

        cancel.setBackground(new java.awt.Color(252, 252, 255));
        cancel.setForeground(new java.awt.Color(0, 156, 220));
        cancel.setText("Cancel");
        cancel.setFocusable(false);
        cancel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 130, 50));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void jcloseAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcloseAdd1ActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_jcloseAdd1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
        fdb.addFavorite(BookExpand.bp.getBookID(),UserSession.getInstance().getUser().getUserID());
        FavoriteAdd.this.bookexpand.execute(BookExpand.bp.getBookID());
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_addActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomizedClasses.RoundedBorderButton add;
    private CustomizedClasses.RoundedBorderButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JButton jcloseAdd1;
    // End of variables declaration//GEN-END:variables
}
