/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.FavoriteDB;
import Classes.UserSession;
import CustomizedClasses.GlassPanePopup;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Aesthetics
 */
public class FavoriteRemove extends javax.swing.JPanel {

    FavoriteDB fdb;
    BookExpand bookexpand;

    /**
     * Creates new form FavoriteRemove
     */
    public FavoriteRemove(BookExpand bookexpand) {
        initComponents();
        fdb = new FavoriteDB();
        this.bookexpand = bookexpand;
    }
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcloseAdd2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cancel = new CustomizedClasses.RoundedBorderButton();
        add = new CustomizedClasses.RoundedBorderButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcloseAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/close.png"))); // NOI18N
        jcloseAdd2.setBorder(null);
        jcloseAdd2.setBorderPainted(false);
        jcloseAdd2.setContentAreaFilled(false);
        jcloseAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcloseAdd2ActionPerformed(evt);
            }
        });
        add(jcloseAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, 40));

        jLabel18.setFont(new java.awt.Font("Poppins", 1, 32)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(42, 42, 42));
        jLabel18.setText("Remove to Favorites");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 360, 30));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setText("You are about to remove this book from your ");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 400, 30));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setText("favorites. Choose to proceed.");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 400, 40));

        cancel.setBackground(new java.awt.Color(252, 252, 255));
        cancel.setForeground(new java.awt.Color(0, 156, 220));
        cancel.setText("Cancel");
        cancel.setFocusable(false);
        cancel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 130, 50));

        add.setBackground(new java.awt.Color(0, 156, 220));
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Remove");
        add.setFocusable(false);
        add.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 160, 50));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void jcloseAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcloseAdd2ActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_jcloseAdd2ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_cancelActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
        fdb.removeFavorite(BookExpand.bp.getBookID(),UserSession.getInstance().getUser().getUserID());
        FavoriteRemove.this.bookexpand.execute(BookExpand.bp.getBookID());
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomizedClasses.RoundedBorderButton add;
    private CustomizedClasses.RoundedBorderButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JButton jcloseAdd2;
    // End of variables declaration//GEN-END:variables
}
