/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import Classes.UserDB;
import javax.swing.JOptionPane;

/**
 *
 * @author Aesthetics
 */
public class ForgotPassword extends javax.swing.JFrame {

    String pass;
    String enteredUser;
    UserDB db;

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        ChangePass.setVisible(false);
        Username.setVisible(true);
        this.db = new UserDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Username = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        note = new javax.swing.JLabel();
        Next = new CustomizedClasses.RoundedBorderButton();
        ChangePass = new javax.swing.JPanel();
        changepassfield = new javax.swing.JPasswordField();
        changepasstitle = new javax.swing.JLabel();
        Submit = new CustomizedClasses.RoundedBorderButton();
        roundedBorderButton1 = new CustomizedClasses.RoundedBorderButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 26, 26));
        jLabel2.setText("Forgot Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 330, 60));

        jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 80, 130, -1));

        Username.setBackground(new java.awt.Color(252, 252, 252));
        Username.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(26, 26, 26));
        username.setText("Username");
        Username.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 40));

        usernamefield.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        usernamefield.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });
        Username.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 380, 50));

        note.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        note.setForeground(new java.awt.Color(82, 82, 82));
        note.setText("Enter your username that you used to register.");
        Username.add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 310, -1));

        Next.setBackground(new java.awt.Color(0, 156, 220));
        Next.setForeground(new java.awt.Color(255, 255, 255));
        Next.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        Next.setLabel("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        Username.add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 380, 50));

        jPanel2.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 410, 230));

        ChangePass.setBackground(new java.awt.Color(252, 252, 252));
        ChangePass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        changepassfield.setForeground(new java.awt.Color(26, 26, 26));
        changepassfield.setToolTipText("");
        changepassfield.setActionCommand("<Not Set>");
        changepassfield.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        changepassfield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        changepassfield.setDoubleBuffered(true);
        changepassfield.setDragEnabled(true);
        changepassfield.setMargin(new java.awt.Insets(2, 10, 2, 10));
        changepassfield.setName(""); // NOI18N
        changepassfield.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                changepassfieldComponentHidden(evt);
            }
        });
        changepassfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassfieldActionPerformed(evt);
            }
        });
        ChangePass.add(changepassfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 380, 50));

        changepasstitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        changepasstitle.setForeground(new java.awt.Color(26, 26, 26));
        changepasstitle.setText("Change Password");
        changepasstitle.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                changepasstitleComponentHidden(evt);
            }
        });
        ChangePass.add(changepasstitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 40));

        Submit.setBackground(new java.awt.Color(0, 156, 220));
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Submit");
        Submit.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        ChangePass.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 380, 60));

        roundedBorderButton1.setBackground(new java.awt.Color(252, 252, 252));
        roundedBorderButton1.setForeground(new java.awt.Color(0, 156, 220));
        roundedBorderButton1.setText("Go Back");
        roundedBorderButton1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        roundedBorderButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedBorderButton1ActionPerformed(evt);
            }
        });
        ChangePass.add(roundedBorderButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 380, 60));

        jPanel2.add(ChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 410, 230));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 480, 790));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/sidebackground.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setIconTextGap(1);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 800));

        setSize(new java.awt.Dimension(1216, 798));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void changepassfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changepassfieldActionPerformed

    private void changepassfieldComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_changepassfieldComponentHidden
        // TODO add your handling code here:

    }//GEN-LAST:event_changepassfieldComponentHidden

    private void changepasstitleComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_changepasstitleComponentHidden
        // TODO add your handling code here:

    }//GEN-LAST:event_changepasstitleComponentHidden

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Login myLogin = new Login();
        myLogin.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        pass = changepassfield.getText();
        db.updatePassword(enteredUser, pass);
        JOptionPane.showMessageDialog(null, "Changed Password Successfully", "Change Password", JOptionPane.PLAIN_MESSAGE);
        Login myLogin = new Login();
        myLogin.show();
        dispose();
    }//GEN-LAST:event_SubmitActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        enteredUser = usernamefield.getText();
        if (db.getUser(enteredUser) != null) {
            ChangePass.setVisible(true);
            Username.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "We're sorry. We couldn't find such username.", "Username not found", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_NextActionPerformed

    private void roundedBorderButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedBorderButton1ActionPerformed
        // TODO add your handling code here:
        ChangePass.setVisible(false);
        Username.setVisible(true);
    }//GEN-LAST:event_roundedBorderButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ForgotPassword().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChangePass;
    private CustomizedClasses.RoundedBorderButton Next;
    private CustomizedClasses.RoundedBorderButton Submit;
    private javax.swing.JPanel Username;
    private javax.swing.JPasswordField changepassfield;
    private javax.swing.JLabel changepasstitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel note;
    private CustomizedClasses.RoundedBorderButton roundedBorderButton1;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
