/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JPanel;

/**
 *
 * @author Aesthetics
 */
public final class GenrePanel extends javax.swing.JPanel {
    
    private JPanel myProducts;

    public int calculatePanel(int num) {
        int height = (num / 4) * 400;
        if (num % 4 != 0) {
            height += 360;
        }
        return height + 200;
    }
    private int num;

    public int getNum() {
        return num;
    }

    public void setNum(int num) {
        this.num = num;
    }

    public JPanel getMyProducts() {
        return myProducts;
    }

    public void setMyProducts() {
        this.myProducts = bookProducts;
    }
    public void addMyProducts(BookPanel bookpanel){
        this.myProducts.add(bookpanel);
    }
    public void setBookProductsHeight(){
        bookProducts.setPreferredSize(new Dimension(900,calculatePanel(this.num)));
        bookProducts.setMaximumSize(new Dimension(900,calculatePanel(this.num)));
        bookProducts.setMinimumSize(new Dimension(900,calculatePanel(this.num)));
        bookProducts.setSize(new Dimension(900,calculatePanel(this.num)));
    }
     public void setGenreNameHeight(){
        genreName.setPreferredSize(new Dimension(900,calculatePanel(this.num)));
        genreName.setMaximumSize(new Dimension(900,calculatePanel(this.num)));
        genreName.setMinimumSize(new Dimension(900,calculatePanel(this.num)));
        genreName.setSize(new Dimension(900,calculatePanel(this.num)));
    }
    
//    
    Dimension sizedefault = new Dimension(910,360);

    public GenrePanel(String genreID, String genre,Icon Header) {
        initComponents();
        this.myProducts = bookProducts;
        this.setBorder(BorderFactory.createLineBorder(Color.black));
        this.setBackground(new Color(252,252,252));
        this.setName(genre);
        header.setIcon(Header);
        header.setAlignmentX(0);
        header.setAlignmentY(0);
        bookProducts.setBackground(new Color(252,252,252));

        
        jScrollPane2.setViewportView(genreName);
        jScrollPane2.setScrollSpeed(5);
        title.setText(genre+ " " + "Books");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new CustomizedClasses.ScrollPaneWin11();
        jPanel1 = new javax.swing.JPanel();
        genreName = new javax.swing.JPanel();
        subTitle = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        jseparator = new javax.swing.JLabel();
        bookProducts = new javax.swing.JPanel();

        setAutoscrolls(true);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genreName.setBackground(new java.awt.Color(252, 252, 252));
        genreName.setAutoscrolls(true);
        genreName.setMaximumSize(new java.awt.Dimension(900, 700));
        genreName.setMinimumSize(new java.awt.Dimension(900, 700));
        genreName.setPreferredSize(new java.awt.Dimension(900, 700));
        genreName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subTitle.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        subTitle.setText("Top picks for today");
        genreName.add(subTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 40));

        title.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        title.setText("Hi, Cedric");
        genreName.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 500, 40));
        genreName.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 143));

        jseparator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jseparator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/separator.png"))); // NOI18N
        genreName.add(jseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 800, 30));

        bookProducts.setBackground(new java.awt.Color(252, 252, 252));
        bookProducts.setAutoscrolls(true);
        bookProducts.setMaximumSize(new java.awt.Dimension(900, 700));
        bookProducts.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 3));
        genreName.add(bookProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 840, -1));

        jPanel1.add(genreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        jScrollPane2.setViewportView(jPanel1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 660));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookProducts;
    private javax.swing.JPanel genreName;
    private javax.swing.JLabel header;
    private javax.swing.JPanel jPanel1;
    private CustomizedClasses.ScrollPaneWin11 jScrollPane2;
    private javax.swing.JLabel jseparator;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
