/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import CustomizedClasses.ProgressBarCustom;

/**
 *
 * @author Aesthetics
 */
public class LoadingPanel extends javax.swing.JPanel {
    public ProgressBarCustom getProgress() {
        return progress;
    }

    public void setProgress(ProgressBarCustom progress) {
        this.progress = progress;
        this.progress.setString(Integer.toString(progress.getValue()));
    }
    
    /**
     * Creates new form LoadingPanel
     */
    public LoadingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loading = new javax.swing.JLabel();
        progress = new CustomizedClasses.ProgressBarCustom();
        gif = new javax.swing.JLabel();
        upbook = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loading.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        loading.setForeground(new java.awt.Color(52, 52, 52));
        loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loading.setText("Loading all books...");
        jPanel1.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 180, -1));

        progress.setBackground(new java.awt.Color(242, 242, 242));
        progress.setBorder(null);
        progress.setForeground(new java.awt.Color(227, 17, 104));
        progress.setColorString(new java.awt.Color(52, 52, 52));
        jPanel1.add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 550, 5));

        gif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/Coffee.gif"))); // NOI18N
        jPanel1.add(gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 160, 120));

        upbook.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        upbook.setForeground(new java.awt.Color(0, 156, 242));
        upbook.setText("UpBook");
        upbook.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(upbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 290, 120, 39));

        welcome.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        welcome.setForeground(new java.awt.Color(52, 52, 52));
        welcome.setText("Welcome To");
        welcome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, 39));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel gif;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loading;
    private CustomizedClasses.ProgressBarCustom progress;
    private javax.swing.JLabel upbook;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
