/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;
import static javax.swing.SwingConstants.CENTER;

/**
 *
 * @author Aesthetics
 */
public class MenuItem extends javax.swing.JPanel {

    private ArrayList<MenuItem> subMenu = new ArrayList<>();
    
    public MenuItem() {
    }

    public ArrayList<MenuItem> getSubMenu() {
        return subMenu;
    }

    public void addSubMenu(MenuItem menu) {
        subMenu.add(menu);
        menu.setVisible(false);
    }

    public void setSubMenu(ArrayList<MenuItem> menu) {
        this.subMenu = menu;
    }

    private ActionListener act;

    public void setAct(ActionListener act) {
        if (act != null) {
            this.act = act;
        }
    }

    String genrename;

    public void setGenreName(String name) {
        this.genrename = name;
    }

    public String getGenreName() {
        return genrename;
    }

    public MenuItem(Icon icon, String menuName, ActionListener act, ArrayList<MenuItem> menu) {
        initComponents();
        this.genrename = menuName;
        lbIcon.setIcon(icon);
        lbName.setText(menuName);

        lbIcon.setHorizontalAlignment(CENTER);
        lbIcon.setHorizontalTextPosition(CENTER);
        if (act != null) {
            this.act = act;
        }
        this.setSize(new Dimension(Integer.MAX_VALUE, 70));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 70));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 70));

        for (int i = 0; i < menu.size(); i++) {
            subMenu.add(menu.get(i));
            menu.get(i).setVisible(false);
        }
    }

    public MenuItem(Icon icon, String menuName, ActionListener act) {
        initComponents();
        this.genrename = menuName;
        lbIcon.setIcon(icon);
        lbName.setText(menuName);
        lbIcon.setHorizontalAlignment(CENTER);
        lbIcon.setHorizontalTextPosition(CENTER);
        if (act != null) {
            this.act = act;
        }
        this.setSize(new Dimension(Integer.MAX_VALUE, 70));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 70));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 70));
    }

    public MenuItem(Icon icon, String menuName) {
        initComponents();
        this.genrename = menuName;
        lbIcon.setIcon(icon);
        lbName.setText(menuName);
        lbIcon.setHorizontalAlignment(CENTER);
        lbIcon.setHorizontalTextPosition(CENTER);
        this.setSize(new Dimension(Integer.MAX_VALUE, 70));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 70));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 70));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 246, 246)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbName.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lbName.setText("Menu Name Here ...");
        add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 180, 70));
        add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 70));
    }// </editor-fold>//GEN-END:initComponents
    private boolean showing = false;

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        if (showing) {
            hideMenu();
            showing = false;

        } else {
            showMenu();
            showing = true;
        }
        if (act != null) {
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_formMousePressed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_formFocusLost
    private void showMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < subMenu.size(); i++) {
                    sleep();
                    subMenu.get(i).setVisible(true);
                }
                showing = true;
                getParent().repaint();
                getParent().revalidate();
            }
        }).start();
    }

    private void hideMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = subMenu.size() - 1; i >= 0; i--) {
                    sleep();
                    subMenu.get(i).setVisible(false);
                    subMenu.get(i).hideMenu();
                }
                getParent().repaint();
                getParent().revalidate();
                showing = false;
            }
        }).start();
    }

    private void sleep() {
        try {
            Thread.sleep(20);
        } catch (Exception e) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables
}
