/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.UserSession;
import CustomizedClasses.GlassPanePopup;
import java.util.List;

/**
 *
 * @author Aesthetics
 */
public class PaymentLogin extends javax.swing.JPanel {

    String paymentMethod;
    List<String> checkoutID;
    Double Amount;
    Executable executable;

    public Executable getExecutable() {
        return executable;
    }

    public void setExecutable(Executable executable) {
        this.executable = executable;
    }
    
    
    /**
     * Creates new form PaymentLogin
     */
    public PaymentLogin(String paymentMethod, List<String> checkoutID, Double Amount) {
        initComponents();
        this.paymentMethod = paymentMethod;
        this.checkoutID = checkoutID;
        this.Amount = Amount;
        amount.setText(Double.toString(Amount)+"0");
    }

    public String formatPhoneNum(String phoneNum) {
        String phone = phoneNum.replaceAll("\\s|-", "");
        phone = phone.replaceAll("[()]", "");
        String newPhone = phone.replaceAll("\\+63", "0");
        return newPhone;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jMerchant = new javax.swing.JLabel();
        jAmount = new javax.swing.JLabel();
        merchant = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        bottom = new javax.swing.JPanel();
        PHLabel = new javax.swing.JLabel();
        jLoginTitle = new javax.swing.JLabel();
        jPhoneNum = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        phoneNum = new javax.swing.JFormattedTextField();
        login = new CustomizedClasses.CustomButton();
        shadow = new javax.swing.JLabel();
        gradientPanel = new CustomizedClasses.GradientPanel();
        gcash = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top.setBackground(new java.awt.Color(251, 251, 251));
        top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMerchant.setBackground(new java.awt.Color(155, 155, 155));
        jMerchant.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jMerchant.setForeground(new java.awt.Color(155, 155, 155));
        jMerchant.setText("Merchant");
        top.add(jMerchant, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 87, -1));

        jAmount.setBackground(new java.awt.Color(155, 155, 155));
        jAmount.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jAmount.setForeground(new java.awt.Color(155, 155, 155));
        jAmount.setText("Amount Due");
        top.add(jAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        merchant.setBackground(new java.awt.Color(155, 155, 155));
        merchant.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        merchant.setForeground(new java.awt.Color(155, 155, 155));
        merchant.setText("UpBook");
        top.add(merchant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 87, -1));

        amount.setBackground(new java.awt.Color(155, 155, 155));
        amount.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        amount.setForeground(new java.awt.Color(0, 125, 254));
        amount.setText("PHP 540.00");
        top.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        main.add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 110));

        bottom.setBackground(new java.awt.Color(255, 255, 255));
        bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PHLabel.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        PHLabel.setForeground(new java.awt.Color(155, 155, 155));
        PHLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PHLabel.setText("+63");
        bottom.add(PHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 110, 40, 40));

        jLoginTitle.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLoginTitle.setText("Login to pay with GCash");
        bottom.add(jLoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 380, 37));

        jPhoneNum.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jPhoneNum.setForeground(new java.awt.Color(155, 155, 155));
        jPhoneNum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPhoneNum.setText("Phone Number");
        bottom.add(jPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 90, 130, 20));

        jSeparator1.setForeground(new java.awt.Color(182, 182, 182));
        bottom.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 150, 230, 10));

        phoneNum.setBorder(null);
        phoneNum.setForeground(new java.awt.Color(155, 155, 155));
        phoneNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        phoneNum.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        bottom.add(phoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 40));

        login.setBackground(new java.awt.Color(1, 89, 223));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("NEXT");
        login.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        bottom.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 300, 50));

        main.add(bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 380, 290));

        add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 380, 400));

        shadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/shadow.png"))); // NOI18N
        shadow.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(shadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 147, 550, 430));

        gradientPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gcash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gcash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/GCash_1.png"))); // NOI18N
        gcash.setToolTipText("");
        gradientPanel.add(gcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 210, 60));

        back.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/backwhite.png"))); // NOI18N
        back.setText("Back");
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        gradientPanel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 40));

        add(gradientPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 220));
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String phonenum = phoneNum.getText();
        String num = formatPhoneNum("0" + phonenum);
        if (UserSession.getInstance().getUser().getPhoneNum().equals(num)) {
            GlassPanePopup.closePopup("PaymentLogin");
            PaymentForm pf =new PaymentForm(this.paymentMethod, this.checkoutID,this.Amount);
            if(this.executable != null){
                pf.setExecutable(this.executable);
            }
            GlassPanePopup.showPopup(pf);
        } else {
            GlassPanePopup.showPopup(new PhoneError());
        }
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupAll();
    }//GEN-LAST:event_backActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PHLabel;
    private javax.swing.JLabel amount;
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JPanel bottom;
    private javax.swing.JLabel gcash;
    private CustomizedClasses.GradientPanel gradientPanel;
    private javax.swing.JLabel jAmount;
    private javax.swing.JLabel jLoginTitle;
    private javax.swing.JLabel jMerchant;
    private javax.swing.JLabel jPhoneNum;
    private javax.swing.JSeparator jSeparator1;
    private CustomizedClasses.CustomButton login;
    private javax.swing.JPanel main;
    private javax.swing.JLabel merchant;
    private javax.swing.JFormattedTextField phoneNum;
    private javax.swing.JLabel shadow;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
