 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.TransactionDB;
import CustomizedClasses.GlassPanePopup;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author Aesthetics
 */
public class PaymentReceipt extends javax.swing.JPanel {
    TransactionDB tdb;
    String transactionID;
    List<String> checkoutID;
    /**
     * Creates new form PaymentReceipt
     */
    public PaymentReceipt(List<String> checkoutids, String transactionID) {
        initComponents();
        tdb = new TransactionDB();
        this.checkoutID = checkoutids;
        this.transactionID = transactionID;
        this.TransactionID.setText(transactionID);
        SimpleDateFormat sdf = new SimpleDateFormat("M/d/yyyy h:mm a");
        Timestamp date = tdb.getTransactionDate(transactionID);
        String formattedTimestamp = sdf.format(date);
        DateandTime.setText(formattedTimestamp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        TransactionID = new javax.swing.JLabel();
        DateandTime = new javax.swing.JLabel();
        receipt = new javax.swing.JLabel();
        gradientPanel2 = new CustomizedClasses.GradientPanel();
        checkoutSummary = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(1, 89, 223));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/download.png"))); // NOI18N
        jButton1.setText("Download Receipt");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, 230, 40));

        TransactionID.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TransactionID.setForeground(new java.awt.Color(52, 52, 52));
        TransactionID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TransactionID.setText("Reference No. 0112348840");
        add(TransactionID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 250, 70));

        DateandTime.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        DateandTime.setForeground(new java.awt.Color(26, 26, 26));
        DateandTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateandTime.setText("05/07/2025 07:18 PM");
        add(DateandTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 140, 50));

        receipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/receiptwithshadow.png"))); // NOI18N
        add(receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 550, 750));

        gradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkoutSummary.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        checkoutSummary.setForeground(new java.awt.Color(255, 255, 255));
        checkoutSummary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/backwhite.png"))); // NOI18N
        checkoutSummary.setText("Checkout Summary");
        checkoutSummary.setBorderPainted(false);
        checkoutSummary.setContentAreaFilled(false);
        checkoutSummary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        checkoutSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutSummaryActionPerformed(evt);
            }
        });
        gradientPanel2.add(checkoutSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 40));

        add(gradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 220));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutSummaryActionPerformed
        // TODO add your handling code here:G
        GlassPanePopup.closePopupAll();
        GlassPanePopup.showPopup(new CheckoutSummary(this.checkoutID,transactionID));
    }//GEN-LAST:event_checkoutSummaryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateandTime;
    private javax.swing.JLabel TransactionID;
    private javax.swing.JButton checkoutSummary;
    private CustomizedClasses.GradientPanel gradientPanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel receipt;
    // End of variables declaration//GEN-END:variables
}
