/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Book;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Aesthetics
 */
public class PendingBooksPanel extends javax.swing.JPanel {

    
    public PendingBooksPanel(Book book, int days, double amount,String id) {
        initComponents();
        
        ImageIcon icon = book.getImage();
        Image original = icon.getImage();
        int newWidth = 60;
        int newHeight = 70;
        Image scaledImage = original.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        checkoutid.setText(id);
        publicationDate.setText(book.getPublicationDate());
        bookID.setText("Book #"+book.getBookID());
        image.setIcon(scaledIcon);
        title.setText(book.getTitle());
        author.setText("by " + book.getAuthorFirstName() + " " + book.getAuthorLastName());
        
        rentedDays.setText(days + " Days");
        totalAmount.setText("Php " + Double.toString(amount)+ "0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        bookID = new javax.swing.JLabel();
        publicationDate = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        rentedDays = new javax.swing.JLabel();
        checkoutid = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 252, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setToolTipText("");
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, 70));

        author.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        author.setForeground(new java.awt.Color(82, 82, 82));
        author.setText("by Colleen Hoover");
        add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 45, 170, 20));

        bookID.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        bookID.setForeground(new java.awt.Color(82, 82, 82));
        bookID.setText("Book ID  #");
        add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, 10));

        publicationDate.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        publicationDate.setForeground(new java.awt.Color(82, 82, 82));
        publicationDate.setText("2018");
        add(publicationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 65, 120, -1));

        title.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        title.setText("jLabel1");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 160, 30));

        totalAmount.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmount.setText("Php 349.00");
        add(totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 5, 90, 80));

        rentedDays.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        rentedDays.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rentedDays.setText("12 Days");
        add(rentedDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 5, 70, 80));

        checkoutid.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        checkoutid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkoutid.setText("12 Days");
        add(checkoutid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 5, 80, 80));

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/pendingboxbooks.png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bookID;
    private javax.swing.JLabel checkoutid;
    private javax.swing.JLabel image;
    private javax.swing.JLabel publicationDate;
    private javax.swing.JLabel rentedDays;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalAmount;
    // End of variables declaration//GEN-END:variables
}
