/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Book;
import Classes.BookDB;
import Classes.Checkout;
import Classes.CheckoutDB;
import Classes.DeliveryAddress;
import Classes.DeliveryDB;
import Classes.Rental;
import Classes.RentalDB;
import Classes.Transaction;
import Classes.TransactionDB;
import Classes.UserCartDB;
import Classes.UserSession;
import CustomizedClasses.GlassPanePopup;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Aesthetics
 */
public class PendingCheckoutExpand extends javax.swing.JPanel {

    RentalDB rdb;
    UserCartDB ucdb;
    CheckoutDB cdb;
    TransactionDB tdb;
    BookDB bdb;
    DeliveryDB ddb;
    int booksize;
    Transaction transaction;
    double totalinitialamount = 0.00, libraryfee = 0.00, deliveryfee = 0.00;
    String deliveryMethod;
    String deliveryaddress;
    String deliverylandmark;
    double sum = 0;
    List<String> checkoutid;
    ArrayList<Checkout> checkouts = new ArrayList<>();
    ArrayList<PendingBooksPanel> pbp = new ArrayList<>();
    ArrayList<Rental> rentals = new ArrayList<>();
    Executable executable;

    public PendingCheckoutExpand(List<String> checkoutID, Executable executable) {
        initComponents();
        this.executable = executable;
        rdb = new RentalDB();
        ucdb = new UserCartDB();
        cdb = new CheckoutDB();
        tdb = new TransactionDB();
        bdb = new BookDB();
        ddb = new DeliveryDB();

        this.booksize = checkoutID.size();
        this.checkoutid = checkoutID;
        for (String id : checkoutID) {
            Checkout checkout = cdb.getCheckout(id, UserSession.getInstance().getUser().getUserID());
            Book book = bdb.getBook(checkout.getBookID());
            DeliveryAddress da = ddb.getAddress(checkout.getAddressID());
            checkouts.add(checkout);
            totalinitialamount += checkout.getTotalAmount();
            libraryfee = checkout.getLibraryFee();
            deliveryfee = checkout.getDeliveryFee();
            if (checkout.getAddressID() != 0) {
                deliveryMethod = "Delivery";
                deliveryaddress = da.getAddress();
                deliverylandmark = da.getLandmark();
            } else {
                deliveryMethod = "Pickup";
                deliveryaddress = "City Hall Lapu-Lapu City Cebu";
                deliverylandmark = "Library City Hall public";
            }
            PendingBooksPanel pbpanel = new PendingBooksPanel(book, checkout.getDays(), checkout.getTotalAmount(),id);
            pbp.add(pbpanel);
        }

        //setting up delivery address
        method.setText(deliveryMethod);
        address.setText(deliveryaddress);
        landmark.setText(deliverylandmark);

        //setting up order details 
        totalBooks.setText(Integer.toString(checkoutID.size()));
        libraryFee.setText(Double.toString(libraryfee) + "0");
        deliveryFee.setText(Double.toString(deliveryfee) + "0");
        initialAmount.setText(Double.toString(totalinitialamount) + "0");
        this.sum = totalinitialamount + libraryfee + deliveryfee;
        totalAmount.setText(Double.toString(sum) + "0");
        int num = loadBooks(bookslist, pbp);
        bookslist.setPreferredSize(new Dimension(510, calculatePanelHeight(num)));
    }

    public int calculatePanelHeight(int numBooks) {
        int height = numBooks * 105;
        return height;

    }

    private int loadBooks(Container container, ArrayList<PendingBooksPanel> p) {
        int count = 0;
        container.removeAll();
        for (int i = 0; i < p.size(); i++) {
            container.add(p.get(i));
            count++;
        }
        return count;
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentGroup = new javax.swing.ButtonGroup();
        title1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        title2 = new javax.swing.JLabel();
        DeliveryTitle1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTotalBooks = new javax.swing.JLabel();
        jLibraryFee = new javax.swing.JLabel();
        jLibraryFee1 = new javax.swing.JLabel();
        jinitialAmount = new javax.swing.JLabel();
        OrderTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        totalAmount = new javax.swing.JLabel();
        close = new CustomizedClasses.RoundedBorderButton();
        PaymentTitle = new javax.swing.JLabel();
        jDeliveryMethod = new javax.swing.JLabel();
        jAddress = new javax.swing.JLabel();
        jLandmark = new javax.swing.JLabel();
        DeliveryTitle = new javax.swing.JLabel();
        method = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        landmark = new javax.swing.JLabel();
        totalBooks = new javax.swing.JLabel();
        libraryFee = new javax.swing.JLabel();
        deliveryFee = new javax.swing.JLabel();
        initialAmount = new javax.swing.JLabel();
        jTotalAmount2 = new javax.swing.JLabel();
        button1 = new CustomizedClasses.RoundedBorderButton();
        button2 = new CustomizedClasses.RoundedBorderButton();
        cash = new CustomizedClasses.RadioButtonCustom();
        gcash = new CustomizedClasses.RadioButtonCustom();
        scrollPaneWin111 = new CustomizedClasses.ScrollPaneWin11();
        jPanel2 = new javax.swing.JPanel();
        bookslist = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(0, 156, 252));
        title1.setText("Pending");
        add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, 120, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/backsmall.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 35, 30, 40));

        title2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        title2.setText("Checkout");
        add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 35, 190, 40));

        DeliveryTitle1.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        DeliveryTitle1.setForeground(new java.awt.Color(32, 32, 32));
        DeliveryTitle1.setText("Checkout Books");
        add(DeliveryTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 230, -1));

        jPanel1.setBackground(new java.awt.Color(252, 253, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTotalBooks.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTotalBooks.setForeground(new java.awt.Color(104, 104, 104));
        jTotalBooks.setText("Total Books            ");
        jPanel1.add(jTotalBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 20));

        jLibraryFee.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLibraryFee.setForeground(new java.awt.Color(104, 104, 104));
        jLibraryFee.setText("Library Fee             ");
        jPanel1.add(jLibraryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 365, 130, 20));

        jLibraryFee1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLibraryFee1.setForeground(new java.awt.Color(104, 104, 104));
        jLibraryFee1.setText("Delivery Fee          ");
        jPanel1.add(jLibraryFee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 130, 20));

        jinitialAmount.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jinitialAmount.setForeground(new java.awt.Color(104, 104, 104));
        jinitialAmount.setText("Books Amount      ");
        jPanel1.add(jinitialAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 415, 130, 20));

        OrderTitle.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        OrderTitle.setForeground(new java.awt.Color(32, 32, 32));
        OrderTitle.setText("Order Details");
        jPanel1.add(OrderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 240, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 340, 10));

        totalAmount.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        totalAmount.setForeground(new java.awt.Color(55, 55, 55));
        totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalAmount.setText("Total Amount");
        jPanel1.add(totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 130, 30));

        close.setBackground(new java.awt.Color(252, 253, 255));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/close.png"))); // NOI18N
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 40, 40));

        PaymentTitle.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        PaymentTitle.setForeground(new java.awt.Color(32, 32, 32));
        PaymentTitle.setText("Payment Details");
        jPanel1.add(PaymentTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 230, 20));

        jDeliveryMethod.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jDeliveryMethod.setForeground(new java.awt.Color(105, 105, 105));
        jDeliveryMethod.setText("Delivery Method");
        jPanel1.add(jDeliveryMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 95, 150, 20));

        jAddress.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jAddress.setForeground(new java.awt.Color(105, 105, 105));
        jAddress.setText("Location");
        jPanel1.add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 130, 20));

        jLandmark.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLandmark.setForeground(new java.awt.Color(105, 105, 105));
        jLandmark.setText("Landmark");
        jPanel1.add(jLandmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 145, 150, 20));

        DeliveryTitle.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        DeliveryTitle.setForeground(new java.awt.Color(32, 32, 32));
        DeliveryTitle.setText("Delivery Details");
        jPanel1.add(DeliveryTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 230, 20));

        method.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        method.setForeground(new java.awt.Color(104, 104, 104));
        method.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        method.setText("Pickup");
        jPanel1.add(method, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 95, 150, 20));

        address.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(104, 104, 104));
        address.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        address.setText("Location");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 220, 20));

        landmark.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        landmark.setForeground(new java.awt.Color(104, 104, 104));
        landmark.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        landmark.setText("Landmark:");
        jPanel1.add(landmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 145, 220, 20));

        totalBooks.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        totalBooks.setForeground(new java.awt.Color(104, 104, 104));
        totalBooks.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalBooks.setText("Total Books");
        jPanel1.add(totalBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 160, 20));

        libraryFee.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        libraryFee.setForeground(new java.awt.Color(104, 104, 104));
        libraryFee.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        libraryFee.setText("Library Fee");
        jPanel1.add(libraryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 365, 160, 20));

        deliveryFee.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        deliveryFee.setForeground(new java.awt.Color(104, 104, 104));
        deliveryFee.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        deliveryFee.setText("Delivery Fee");
        jPanel1.add(deliveryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 160, 20));

        initialAmount.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        initialAmount.setForeground(new java.awt.Color(104, 104, 104));
        initialAmount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        initialAmount.setText("Books Amount");
        jPanel1.add(initialAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 415, 160, 20));

        jTotalAmount2.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jTotalAmount2.setForeground(new java.awt.Color(55, 55, 55));
        jTotalAmount2.setText("Total Amount  ");
        jPanel1.add(jTotalAmount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 130, 30));

        button1.setBackground(new java.awt.Color(0, 156, 220));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Pay Checkout");
        button1.setToolTipText("");
        button1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 160, 50));

        button2.setBackground(new java.awt.Color(252, 253, 255));
        button2.setForeground(new java.awt.Color(52, 52, 52));
        button2.setText("Cancel Checkout");
        button2.setToolTipText("");
        button2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 160, 50));

        cash.setBackground(new java.awt.Color(0, 156, 220));
        paymentGroup.add(cash);
        cash.setForeground(new java.awt.Color(82, 82, 82));
        cash.setText("Cash");
        cash.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cash.setIconTextGap(6);
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });
        jPanel1.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        gcash.setBackground(new java.awt.Color(0, 156, 220));
        paymentGroup.add(gcash);
        gcash.setForeground(new java.awt.Color(82, 82, 82));
        gcash.setText("GCash");
        gcash.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        gcash.setIconTextGap(6);
        gcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcashActionPerformed(evt);
            }
        });
        jPanel1.add(gcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 430, 620));

        scrollPaneWin111.setBorder(null);
        scrollPaneWin111.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookslist.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0);
        flowLayout2.setAlignOnBaseline(true);
        bookslist.setLayout(flowLayout2);
        jPanel2.add(bookslist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 400));

        scrollPaneWin111.setViewportView(jPanel2);

        add(scrollPaneWin111, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 510, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        int max = 3 - rdb.countRentalActive(UserSession.getInstance().getUser().getUserID());
        ArrayList<Checkout> checkouts = new ArrayList<>();
        boolean flag = false;

        for (String id : this.checkoutid) {
            Checkout ck = cdb.getCheckout(id, UserSession.getInstance().getUser().getUserID());
            if (rdb.inActiveRental(UserSession.getInstance().getUser().getUserID(), ck.getBookID())) {
                flag = true;
                break;
            }
        }

        if (max > 0 && this.booksize <= max) {

            if (!flag) {
                String pm = null;
                if (cash.isSelected()) {
                    pm = "Cash";

                    String transactionID = tdb.createTransaction(UserSession.getInstance().getUser().getUserID(), pm, this.sum, this.sum, "Done");
                    cdb.setTransactionCheckout(transactionID, this.checkoutid, "Confirmed", UserSession.getInstance().getUser().getUserID());

                    //create rentals
                    rentals = cdb.getCheckouts(this.checkoutid, UserSession.getInstance().getUser().getUserID());
                    for (Rental rental : rentals) {
                        rdb.createRental(rental);
                        bdb.removeBookInventory(rental.getBookID());
                    }
                    this.executable.executeCurrentRentals();
                    this.executable.executePendingCheckout();
                    this.executable.executeCheckoutHistory();
                    GlassPanePopup.closePopupLast();
                    GlassPanePopup.showPopup(new CheckoutSummary(this.checkoutid, transactionID));
                } else if (gcash.isSelected()) {
                    pm = "Gcash";
                    PaymentLogin pl = new PaymentLogin(pm, this.checkoutid, this.sum);
                    pl.setExecutable(this.executable);
                    GlassPanePopup.showPopup(pl);
                }
            } else {
                JOptionPane.showMessageDialog(null, "One of the books is currently rented.", "Already Rented", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "You have reached the maximum renting of books.", "Maximum Rented", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        for (String id : this.checkoutid) {
//            cdb.removeCheckout(id);
            cdb.updateCheckout(id,"Failed");
        }
        this.executable.executePendingCheckout();
        this.executable.executeCheckoutHistory();
        GlassPanePopup.closePopupAll();
    }//GEN-LAST:event_button2ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_closeActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashActionPerformed

    private void gcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gcashActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeliveryTitle;
    private javax.swing.JLabel DeliveryTitle1;
    private javax.swing.JLabel OrderTitle;
    private javax.swing.JLabel PaymentTitle;
    private javax.swing.JLabel address;
    private javax.swing.JPanel bookslist;
    private CustomizedClasses.RoundedBorderButton button1;
    private CustomizedClasses.RoundedBorderButton button2;
    private CustomizedClasses.RadioButtonCustom cash;
    private CustomizedClasses.RoundedBorderButton close;
    private javax.swing.JLabel deliveryFee;
    private CustomizedClasses.RadioButtonCustom gcash;
    private javax.swing.JLabel initialAmount;
    private javax.swing.JLabel jAddress;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jDeliveryMethod;
    private javax.swing.JLabel jLandmark;
    private javax.swing.JLabel jLibraryFee;
    private javax.swing.JLabel jLibraryFee1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jTotalAmount2;
    private javax.swing.JLabel jTotalBooks;
    private javax.swing.JLabel jinitialAmount;
    private javax.swing.JLabel landmark;
    private javax.swing.JLabel libraryFee;
    private javax.swing.JLabel method;
    private javax.swing.ButtonGroup paymentGroup;
    private CustomizedClasses.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JLabel totalBooks;
    // End of variables declaration//GEN-END:variables
}
