/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Checkout;
import CustomizedClasses.GlassPanePopup;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author Aesthetics
 */
public class PendingCheckout extends javax.swing.JPanel {

    Timestamp date;
    ArrayList<Checkout> checkouts = new ArrayList<>();
    SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy");
    String formattedDate;
    Double totalAmount = 0.00;
    List<String> checkoutid = new ArrayList<>();
    Executable executable;
    public PendingCheckout(Timestamp date, ArrayList<Checkout> checkout, Executable executable) {
        initComponents();
        this.date = date;
        this.checkouts = checkout;
        this.executable = executable;
        formattedDate = dateFormat.format(this.date);
        checkoutDate.setText(formattedDate);
        this.totalBooks.setText(Integer.toString(this.checkouts.size())); 
        this.libraryFee.setText(Double.toString(this.checkouts.get(0).getLibraryFee())+"0");
        for(Checkout ck : checkout){
            totalAmount += ck.getTotalAmount();
            this.checkoutid.add(ck.getCheckoutID());
        }
        this.amount.setText(Double.toString(totalAmount)+"0");
        this.status.setText(this.checkouts.get(0).getCheckoutStatus());
        
    }
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 0, 0));
        g2.dispose();
        super.paintComponents(grphcs);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jStatus = new javax.swing.JLabel();
        libraryFee = new javax.swing.JLabel();
        jLibraryFee = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        jAmount = new javax.swing.JLabel();
        jCheckoutDate = new javax.swing.JLabel();
        checkoutDate = new javax.swing.JLabel();
        jTotalBooks = new javax.swing.JLabel();
        totalBooks = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 90));

        status.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        status.setForeground(new java.awt.Color(0, 126, 220));
        status.setText("In Progress");
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 45, 90, 20));

        jStatus.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jStatus.setForeground(new java.awt.Color(113, 113, 113));
        jStatus.setText("Status");
        add(jStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 80, 10));

        libraryFee.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        libraryFee.setForeground(new java.awt.Color(102, 102, 102));
        libraryFee.setText("Php 25.00");
        add(libraryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 45, 110, 20));

        jLibraryFee.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLibraryFee.setForeground(new java.awt.Color(113, 113, 113));
        jLibraryFee.setText("Library Fee");
        add(jLibraryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 80, 10));

        amount.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        amount.setForeground(new java.awt.Color(102, 102, 102));
        amount.setText("Php 192.00");
        add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 45, 110, 20));

        jAmount.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jAmount.setForeground(new java.awt.Color(113, 113, 113));
        jAmount.setText("Amount");
        add(jAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 110, 10));

        jCheckoutDate.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jCheckoutDate.setForeground(new java.awt.Color(113, 113, 113));
        jCheckoutDate.setText("Checkout Date");
        add(jCheckoutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 10));

        checkoutDate.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        checkoutDate.setForeground(new java.awt.Color(82, 82, 82));
        checkoutDate.setText("May 23, 2023");
        add(checkoutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 45, 120, 20));

        jTotalBooks.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTotalBooks.setForeground(new java.awt.Color(113, 113, 113));
        jTotalBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotalBooks.setText("Total Books");
        add(jTotalBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 90, 10));

        totalBooks.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        totalBooks.setForeground(new java.awt.Color(52, 52, 52));
        totalBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBooks.setText("1");
        add(totalBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 45, 90, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new PendingCheckoutExpand(this.checkoutid,this.executable));
    }//GEN-LAST:event_bgMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel checkoutDate;
    private javax.swing.JLabel jAmount;
    private javax.swing.JLabel jCheckoutDate;
    private javax.swing.JLabel jLibraryFee;
    private javax.swing.JLabel jStatus;
    private javax.swing.JLabel jTotalBooks;
    private javax.swing.JLabel libraryFee;
    private javax.swing.JLabel status;
    private javax.swing.JLabel totalBooks;
    // End of variables declaration//GEN-END:variables
}
