/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Rental;
import CustomizedClasses.GlassPanePopup;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;

/**
 *
 * @author Aesthetics
 */
public class RentalBooks extends javax.swing.JPanel {

  private Rental rental;
    
    
    public Rental getRental() {
        return rental;
    }

    public void setRental(Rental rental) {
        this.rental = rental;
    }

    Timestamp timestamp;
    SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy");
    String formattedDate;
    
    public RentalBooks(Rental rental) {
        initComponents();
        this.rental = rental;
   
        rentalID.setText(rental.getRentalID());
        checkoutID.setText(rental.getCheckoutID());
        bookID.setText(rental.getBookID());
        
        //settingup dates
        timestamp = rental.getStartDate();
        formattedDate = dateFormat.format(timestamp);
        startDate.setText(formattedDate);
        
        timestamp = rental.getEndDate();
        formattedDate = dateFormat.format(timestamp);
        endDate.setText(formattedDate);
        
        rentStatus.setText(rental.getRentStatus());
    }
    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLabel();
        rentStatus = new javax.swing.JLabel();
        jRentStatus = new javax.swing.JLabel();
        endDate = new javax.swing.JLabel();
        jEndDate = new javax.swing.JLabel();
        startDate = new javax.swing.JLabel();
        jStartDate = new javax.swing.JLabel();
        jRentalID = new javax.swing.JLabel();
        rentalID = new javax.swing.JLabel();
        bookID = new javax.swing.JLabel();
        jBookID = new javax.swing.JLabel();
        jCheckoutID = new javax.swing.JLabel();
        checkoutID = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 252, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        rentStatus.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        rentStatus.setForeground(new java.awt.Color(21, 180, 106));
        rentStatus.setText("Ongoing");
        add(rentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 90, 20));

        jRentStatus.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jRentStatus.setForeground(new java.awt.Color(255, 255, 255));
        jRentStatus.setText("Status");
        add(jRentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 25, 80, 10));

        endDate.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        endDate.setForeground(new java.awt.Color(52, 52, 52));
        endDate.setText("05/11/25");
        add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 120, 20));

        jEndDate.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jEndDate.setForeground(new java.awt.Color(255, 255, 255));
        jEndDate.setText("End Date");
        add(jEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 25, 120, 10));

        startDate.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        startDate.setForeground(new java.awt.Color(52, 52, 52));
        startDate.setText("05/11/25");
        add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 120, 20));

        jStartDate.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jStartDate.setForeground(new java.awt.Color(255, 255, 255));
        jStartDate.setText("Start Date");
        add(jStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 25, 120, 10));

        jRentalID.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jRentalID.setForeground(new java.awt.Color(255, 255, 255));
        jRentalID.setText("Rental ID");
        add(jRentalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 90, 10));

        rentalID.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        rentalID.setForeground(new java.awt.Color(0, 156, 220));
        rentalID.setText("RN00234");
        rentalID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(rentalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 20));

        bookID.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        bookID.setForeground(new java.awt.Color(52, 52, 52));
        bookID.setText("RN00234");
        add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 110, 20));

        jBookID.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jBookID.setForeground(new java.awt.Color(255, 255, 255));
        jBookID.setText("Book ID");
        add(jBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 25, 110, 10));

        jCheckoutID.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jCheckoutID.setForeground(new java.awt.Color(255, 255, 255));
        jCheckoutID.setText("Checkout ID");
        add(jCheckoutID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 25, 110, 10));

        checkoutID.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        checkoutID.setForeground(new java.awt.Color(52, 52, 52));
        checkoutID.setText("RN00234");
        add(checkoutID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 110, 20));

        bg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg1MousePressed(evt);
            }
        });
        add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new CurrentRentedBooksExpand(this.rental,null));
    }//GEN-LAST:event_bgMousePressed

    private void bg1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bg1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bookID;
    private javax.swing.JLabel checkoutID;
    private javax.swing.JLabel endDate;
    private javax.swing.JLabel jBookID;
    private javax.swing.JLabel jCheckoutID;
    private javax.swing.JLabel jEndDate;
    private javax.swing.JLabel jRentStatus;
    private javax.swing.JLabel jRentalID;
    private javax.swing.JLabel jStartDate;
    private javax.swing.JLabel rentStatus;
    private javax.swing.JLabel rentalID;
    private javax.swing.JLabel startDate;
    // End of variables declaration//GEN-END:variables
}
