/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.BookDB;
import Classes.Rental;
import Classes.RentalDB;
import Classes.UserSession;
import CustomizedClasses.GlassPanePopup;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;

/**
 *
 * @author Aesthetics
 */
public class ReturnBook extends javax.swing.JPanel {

    RentalDB rdb;
    BookDB bdb;
    Rental rental;
    Executable executable;


    public ReturnBook(Rental rental,Executable executable) {
        initComponents();
        this.rental = rental;
        this.executable = executable;
        rdb = new RentalDB();
        bdb = new BookDB();
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        noted = new CustomizedClasses.RoundedBorderButton();
        roundedBorderButton1 = new CustomizedClasses.RoundedBorderButton();
        bg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(42, 42, 42));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Return Book");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 430, 30));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Are you sure you want to return this book?");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 30));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("You still have a few days left before it's return date.");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 430, -1));

        noted.setBackground(new java.awt.Color(0, 156, 220));
        noted.setForeground(new java.awt.Color(255, 255, 255));
        noted.setText("Return Book");
        noted.setFocusable(false);
        noted.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        noted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notedActionPerformed(evt);
            }
        });
        add(noted, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 170, 360, 50));

        roundedBorderButton1.setForeground(new java.awt.Color(0, 156, 220));
        roundedBorderButton1.setText("Cancel and Go Back");
        roundedBorderButton1.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        roundedBorderButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedBorderButton1ActionPerformed(evt);
            }
        });
        add(roundedBorderButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 230, 360, 50));
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void notedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notedActionPerformed
        // TODO add your handling code here:
        Instant instant = Instant.now();
        ZoneId zoneId = ZoneId.systemDefault();
        LocalDateTime localDateTime = LocalDateTime.ofInstant(instant, zoneId);
        Timestamp timestamp = Timestamp.valueOf(localDateTime);
        rdb.completeRental(UserSession.getInstance().getUser().getUserID(), this.rental.getRentalID(), timestamp, "Good");
        bdb.addBookInventory(this.rental.getBookID());
        this.executable.executeCurrentRentals();
        this.executable.executeAllRentals();
        GlassPanePopup.closePopupAll();
    }//GEN-LAST:event_notedActionPerformed

    private void roundedBorderButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedBorderButton1ActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_roundedBorderButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private CustomizedClasses.RoundedBorderButton noted;
    private CustomizedClasses.RoundedBorderButton roundedBorderButton1;
    // End of variables declaration//GEN-END:variables
}
