/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import Classes.UserDB;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.BorderFactory;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author Aesthetics
 */
public class SignUp extends javax.swing.JFrame {

    Color mygrey = new Color(206, 206, 206);
    Color myblue = new Color(0, 145, 220);
    Color myred = new Color(255, 16, 16);
    UserDB db;

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        db = new UserDB();

    }

    public static void setCompoundBorder(JTextField textField, Color color) {
        Border insideBorder = BorderFactory.createEmptyBorder(5, 10, 5, 10);
        Border outsideBorder = BorderFactory.createLineBorder(color, 1, true);
        Border compoundBorder = BorderFactory.createCompoundBorder(outsideBorder, insideBorder);
        textField.setBorder(compoundBorder);
    }

    public String formatPhoneNum(String phoneNum) {
        String phone = phoneNum.replaceAll("\\s|-", "");
        phone = phone.replaceAll("[()]", "");
        String newPhone = phone.replaceAll("\\+63", "0");
        System.out.println(newPhone);
        return newPhone;
    }

    public static boolean isValidEmail(String email) {
        // Regular expression pattern to match email addresses
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";

        // Compile the regular expression pattern into a Pattern object
        Pattern pattern = Pattern.compile(emailRegex);
        // Use the Pattern object to create a Matcher object for the input email
        Matcher matcher = pattern.matcher(email);
        // Return true if the email matches the pattern, false otherwise
        return matcher.matches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFirstName = new javax.swing.JTextField();
        jLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPhoneNum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSignUp = new CustomizedClasses.RoundedBorderButton();
        jLabel10 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 790));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/smallupbooklogo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 140, 49));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 26, 26));
        jLabel3.setText("Sign Up");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 240, 60));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 110, 30));

        jFirstName.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jFirstName.setForeground(new java.awt.Color(206, 206, 206));
        jFirstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFirstName.setText("First Name");
        jFirstName.setToolTipText("");
        jFirstName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jFirstName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFirstName.setDragEnabled(true);
        jFirstName.setInheritsPopupMenu(true);
        jFirstName.setMargin(new java.awt.Insets(10, 20, 10, 20));
        jFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFirstNameFocusLost(evt);
            }
        });
        jFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(jFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 210, 45));

        jLastName.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLastName.setForeground(new java.awt.Color(206, 206, 206));
        jLastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jLastName.setText("Last Name");
        jLastName.setToolTipText("");
        jLastName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jLastName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLastName.setDragEnabled(true);
        jLastName.setInheritsPopupMenu(true);
        jLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLastNameFocusLost(evt);
            }
        });
        jLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(jLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 210, 45));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 110, 30));

        jUsername.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jUsername.setForeground(new java.awt.Color(206, 206, 206));
        jUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jUsername.setText("Enter username");
        jUsername.setToolTipText("");
        jUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jUsername.setDragEnabled(true);
        jUsername.setInheritsPopupMenu(true);
        jUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsernameFocusLost(evt);
            }
        });
        jUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jUsernameMousePressed(evt);
            }
        });
        jPanel1.add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 210, 45));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setText("Username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 110, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setText("Phone Number");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 140, 30));

        jPhoneNum.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jPhoneNum.setForeground(new java.awt.Color(206, 206, 206));
        jPhoneNum.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPhoneNum.setText("+63 xxx  xxx  xxxx");
        jPhoneNum.setToolTipText("");
        jPhoneNum.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jPhoneNum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPhoneNum.setDragEnabled(true);
        jPhoneNum.setInheritsPopupMenu(true);
        jPhoneNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPhoneNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPhoneNumFocusLost(evt);
            }
        });
        jPanel1.add(jPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 210, 45));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 110, 30));

        jEmail.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jEmail.setForeground(new java.awt.Color(206, 206, 206));
        jEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jEmail.setText("sample@email.com");
        jEmail.setToolTipText("");
        jEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jEmail.setDragEnabled(true);
        jEmail.setInheritsPopupMenu(true);
        jEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jEmailFocusLost(evt);
            }
        });
        jPanel1.add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 440, 45));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel11.setText("Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 110, 30));

        jButton1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 156, 220));
        jButton1.setText("Sign in Instead");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, 50));

        jSignUp.setBackground(new java.awt.Color(0, 156, 220));
        jSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jSignUp.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jSignUp.setLabel("Next");
        jSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(jSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 120, 50));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(82, 82, 82));
        jLabel10.setText("Passwords should be at least 6 or more.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 230, -1));

        jPassword.setForeground(new java.awt.Color(206, 206, 206));
        jPassword.setText("******");
        jPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFocusLost(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 440, 45));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/whitebox.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 600, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/Gradient bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 790));

        setSize(new java.awt.Dimension(1216, 798));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Login mylogin = new Login();
        mylogin.show();
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstNameActionPerformed

    private void jUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsernameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameMousePressed

    private void jFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFirstNameFocusGained
        // TODO add your handling code here:
        if (jFirstName.getText().equals("First Name")) {
            jFirstName.setText("");
            jFirstName.setForeground(Color.BLACK);
        }
        setCompoundBorder(jFirstName, myblue);
    }//GEN-LAST:event_jFirstNameFocusGained

    private void jUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusGained
        // TODO add your handling code here:
        if (jUsername.getText().equals("Enter username")) {
            jUsername.setText("");
            jUsername.setForeground(Color.BLACK);
        }
        setCompoundBorder(jUsername, myblue);
    }//GEN-LAST:event_jUsernameFocusGained

    private void jUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusLost
        // TODO add your handling code here:
        if (jUsername.getText().isEmpty()) {
            jUsername.setForeground(mygrey);
            jUsername.setText("Enter username");
        }
        setCompoundBorder(jUsername, mygrey);
    }//GEN-LAST:event_jUsernameFocusLost

    private void jFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFirstNameFocusLost
        // TODO add your handling code here: 
        if (jFirstName.getText().isEmpty()) {
            jFirstName.setForeground(mygrey);
            jFirstName.setText("First Name");
        }
        setCompoundBorder(jFirstName, mygrey);
    }//GEN-LAST:event_jFirstNameFocusLost

    private void jLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLastNameFocusLost
        // TODO add your handling code here:
        if (jLastName.getText().isEmpty()) {
            jLastName.setForeground(mygrey);
            jLastName.setText("Last Name");
        }
        setCompoundBorder(jLastName, mygrey);
    }//GEN-LAST:event_jLastNameFocusLost

    private void jLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLastNameFocusGained
        // TODO add your handling code here:
        if (jLastName.getText().equals("Last Name")) {
            jLastName.setText("");
            jLastName.setForeground(Color.BLACK);
        }
        setCompoundBorder(jLastName, myblue);
    }//GEN-LAST:event_jLastNameFocusGained

    private void jPhoneNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPhoneNumFocusGained
        // TODO add your handling code here:
        if (jPhoneNum.getText().equals("+63 xxx  xxx  xxxx")) {
            jPhoneNum.setText("");
            jPhoneNum.setForeground(Color.BLACK);
        }
        setCompoundBorder(jPhoneNum, myblue);
    }//GEN-LAST:event_jPhoneNumFocusGained

    private void jEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jEmailFocusGained
        // TODO add your handling code here:
        if (jEmail.getText().equals("sample@email.com")) {
            jEmail.setText("");
            jEmail.setForeground(Color.BLACK);
        }
        setCompoundBorder(jEmail, myblue);
    }//GEN-LAST:event_jEmailFocusGained

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        // TODO add your handling code here:
        if (jPassword.getText().equals("******")) {
            jPassword.setText("");
            jPassword.setForeground(Color.BLACK);
        }
        setCompoundBorder(jPassword, myblue);
    }//GEN-LAST:event_jPasswordFocusGained

    private void jPhoneNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPhoneNumFocusLost
        // TODO add your handling code here:
        if (jPhoneNum.getText().isEmpty()) {
            jPhoneNum.setForeground(mygrey);
            jPhoneNum.setText("+63 xxx  xxx  xxxx");
        }
        setCompoundBorder(jPhoneNum, mygrey);
    }//GEN-LAST:event_jPhoneNumFocusLost

    private void jEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jEmailFocusLost
        // TODO add your handling code here:
        if (jEmail.getText().isEmpty()) {
            jEmail.setForeground(mygrey);
            jEmail.setText("sample@email.com");
        }
        setCompoundBorder(jEmail, mygrey);
    }//GEN-LAST:event_jEmailFocusLost

    private void jPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusLost
        // TODO add your handling code here:
        if (jPassword.getText().isEmpty()) {
            jPassword.setForeground(mygrey);
            jPassword.setText("******");
        }
        setCompoundBorder(jPassword, mygrey);
    }//GEN-LAST:event_jPasswordFocusLost

    private void jLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLastNameActionPerformed

    private void jSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSignUpActionPerformed
        // TODO add your handling code here:
        String firstName = jFirstName.getText();
        String lastName = jLastName.getText();
        String username = jUsername.getText();
        String phoneNum = jPhoneNum.getText();
        String newPhone = formatPhoneNum(phoneNum);
        String email = jEmail.getText();
        String password = String.valueOf(jPassword.getPassword());

        if (firstName.isEmpty() || lastName.isEmpty() || username.isEmpty() || phoneNum.isEmpty() || email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all fields", "Try Again", JOptionPane.ERROR_MESSAGE);
            if (firstName.isEmpty()) {
                setCompoundBorder(jFirstName, myred);
            }
            if (lastName.isEmpty()) {
                setCompoundBorder(jLastName, myred);
            }
            if (username.isEmpty()) {
                setCompoundBorder(jUsername, myred);
            }
            if (phoneNum.isEmpty()) {
                setCompoundBorder(jPhoneNum, myred);
            }
            if (email.isEmpty()) {
                setCompoundBorder(jEmail, myred);
            }
            if (password.isEmpty()) {
                setCompoundBorder(jPassword, myred);
            }

        } else if (firstName.equals("First Name") || username.equals("Enter username") || lastName.equals("Last Name") || email.equals("sample@email.com")
                || phoneNum.equals("+63 xxx  xxx  xxxx") || password.equals("******")) {
            if (firstName.equals("First Name")) {
                setCompoundBorder(jFirstName, myred);
            }
            if (lastName.equals("Last Name")) {
                setCompoundBorder(jLastName, myred);
            }
            if (username.equals("Enter username")) {
                setCompoundBorder(jUsername, myred);
            }
            if (phoneNum.equals("+63 xxx  xxx  xxxx")) {
                setCompoundBorder(jPhoneNum, myred);
            }
            if (email.equals("sample@email.com")) {
                setCompoundBorder(jEmail, myred);
            }
            if (password.equals("******")) {
                setCompoundBorder(jPassword, myred);
            }
            JOptionPane.showMessageDialog(this, "Please enter all fields", "Try Again", JOptionPane.ERROR_MESSAGE);

        } else {
            if (db.getUser(username) == null) {
                if (db.isPhoneNumberUnique(newPhone)) {
                    if (newPhone.length() == 11) {
                        if (isValidEmail(email)) {
                            if (password.length() >= 6) {
                                try {
                                    db.createUser(username, firstName, lastName, newPhone, email, password);
                                    if (db.getUser(username) != null) {
                                        JOptionPane.showMessageDialog(null, "You have signed up!");
                                        Login mylogin = new Login();
                                        mylogin.show();
                                        dispose();
                                    }
                                } catch (SQLException ex) {
                                    Logger.getLogger(UserDB.class.getName()).log(Level.SEVERE, null, ex);
                                    JOptionPane.showMessageDialog(null, ex, "Try Again", JOptionPane.ERROR_MESSAGE);
                                }

                            } else {
                                setCompoundBorder(jPassword, myred);
                                JOptionPane.showMessageDialog(this, "Minimum length for password is 6 or more. Please try again.", "Try Again", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            setCompoundBorder(jEmail, myred);
                            JOptionPane.showMessageDialog(this, "Please enter a valid email.", "Try Again", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        setCompoundBorder(jPhoneNum, myred);
                        JOptionPane.showMessageDialog(this, "Please enter the Philippine phone number format.", "Try Again", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    setCompoundBorder(jPhoneNum, myred);
                    JOptionPane.showMessageDialog(this, "This phone number is already been taken.", "Try Again", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                setCompoundBorder(jUsername, myred);
                JOptionPane.showMessageDialog(this, "Username has already been taken", "Try Again", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jFirstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLastName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jPhoneNum;
    private CustomizedClasses.RoundedBorderButton jSignUp;
    private javax.swing.JTextField jUsername;
    // End of variables declaration//GEN-END:variables
}
