/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Classes.Transaction;
import java.awt.Color;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;

/**
 *
 * @author Aesthetics
 */
public class TransactionPanel extends javax.swing.JPanel {

    /**
     * Creates new form TransactionPanel
     */
    SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy");
    String formattedDate;
    Timestamp transactdate;
    public TransactionPanel(Transaction transaction) {
        initComponents();
        id.setText(transaction.getTransactionID());
        transactdate = transaction.getTransactionDate();
        formattedDate = dateFormat.format(transactdate);
        date.setText(formattedDate);
        method.setText(transaction.getPaymentMethod());
        amountPaid.setText("Php "+ Double.toString(transaction.getAmountPaid())+"0");
        amountPay.setText("Php " + Double.toString(transaction.getAmountToPay())+"0");
        if(transaction.getTransactionStatus().equals("Done")){
            status.setForeground(new Color(21,180,106));
        }
        status.setText(transaction.getTransactionStatus());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        method = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        amountPay = new javax.swing.JLabel();
        amountPaid = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 80));

        id.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(0, 156, 220));
        id.setText("Transaction ID");
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 80));

        method.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        method.setForeground(new java.awt.Color(52, 52, 52));
        method.setText("Payment Method");
        add(method, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 120, 80));

        date.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(52, 52, 52));
        date.setText("Transaction Date");
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 110, 80));

        amountPay.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        amountPay.setForeground(new java.awt.Color(52, 52, 52));
        amountPay.setText("Amount to Pay");
        add(amountPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 110, 80));

        amountPaid.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        amountPaid.setForeground(new java.awt.Color(52, 52, 52));
        amountPaid.setText("Amount Paid");
        add(amountPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 110, 80));

        status.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        status.setForeground(new java.awt.Color(0, 156, 220));
        status.setText("Status");
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 80, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bgMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountPaid;
    private javax.swing.JLabel amountPay;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel date;
    private javax.swing.JLabel id;
    private javax.swing.JLabel method;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
