/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Classes.Admin;
import Classes.AdminDB;
import Classes.AdminSession;
import User.Login;
import static User.SignUp.setCompoundBorder;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Aesthetics
 */
public class AdminLogin extends javax.swing.JFrame {

    Color mygrey = new Color(206, 206, 206);
    Color myblue = new Color(0, 145, 220);
    Color myred = new Color(255, 16, 16);
    /**
     * Creates new form AdminLogin
     */
    AdminDB adb;

    public AdminLogin() {
        initComponents();
        adb = new AdminDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 252, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUsername.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jUsername.setForeground(new java.awt.Color(206, 206, 206));
        jUsername.setText("Enter username");
        jUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsernameFocusLost(evt);
            }
        });
        jPanel1.add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 350, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/homelogo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 350, 74));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel2.setText("Admin");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 230, 70));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 130, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 90, 30));

        jPassword.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jPassword.setForeground(new java.awt.Color(206, 206, 206));
        jPassword.setText("******");
        jPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 206), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFocusLost(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 350, 50));

        loginbutton.setBackground(new java.awt.Color(0, 145, 220));
        loginbutton.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 350, 60));

        button1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(42, 42, 42));
        button1.setText("Sign In as User");
        button1.setContentAreaFilled(false);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 240, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 790));

        setSize(new java.awt.Dimension(1216, 798));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        Login mylogin;
        mylogin = new Login();
        mylogin.show();

        dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:

        String username = jUsername.getText();
        String password = String.valueOf(jPassword.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            if (username.isEmpty()) {
                setCompoundBorder(jUsername, myred);
            }
            if (password.isEmpty()) {
                setCompoundBorder(jPassword, myred);
            }
            JOptionPane.showMessageDialog(this, "Please enter all fields.", "Try Again", JOptionPane.ERROR_MESSAGE);
        } else {
            if (adb.checkUsername(username)) {
                if (adb.checkPassword(username, password)) {
                    Admin admin = adb.getAdmin(username);
                    AdminSession.getInstance().setAdmin(admin);
                    JOptionPane.showMessageDialog(null, "Login Successful");
                    AdminHome myHome = new AdminHome();
                    myHome.show();
                    dispose();
                } else {
                    setCompoundBorder(jUsername, myred);
                    setCompoundBorder(jPassword, myred);
                    JOptionPane.showMessageDialog(this, "Your username or password is incorrect. Please try again", "Try Again", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                setCompoundBorder(jUsername, myred);
                setCompoundBorder(jPassword, myred);
                JOptionPane.showMessageDialog(this, "Your username is incorrect. Please try again", "Try Again", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void jUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusGained
        // TODO add your handling code here:

        if (jUsername.getText().equals("Enter username")) {
            jUsername.setText("");
            jUsername.setForeground(Color.BLACK);
        }
        setCompoundBorder(jUsername, myblue);
    }//GEN-LAST:event_jUsernameFocusGained

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        // TODO add your handling code here:
        if (jPassword.getText().equals("******")) {
            jPassword.setText("");
            jPassword.setForeground(Color.BLACK);
        }
        setCompoundBorder(jPassword, myblue);
    }//GEN-LAST:event_jPasswordFocusGained

    private void jUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusLost
        // TODO add your handling code here:
        if (jUsername.getText().isEmpty()) {
            jUsername.setForeground(mygrey);
            jUsername.setText("Enter username");
            setCompoundBorder(jUsername, mygrey);
        } else {
            setCompoundBorder(jUsername, myblue);
        }
    }//GEN-LAST:event_jUsernameFocusLost

    private void jPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusLost
        // TODO add your handling code here:
        if (jPassword.getText().isEmpty()) {
            jPassword.setForeground(mygrey);
            jPassword.setText("******");
            setCompoundBorder(jPassword, mygrey);
        } else {
            setCompoundBorder(jPassword, myblue);
        }
    }//GEN-LAST:event_jPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUsername;
    private javax.swing.JButton loginbutton;
    // End of variables declaration//GEN-END:variables
}
