/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import Classes.Genre;

/**
 *
 * @author Aesthetics
 */
public class GenrePanel extends javax.swing.JPanel {

    /**
     * Creates new form GenrePanel
     */
    public GenrePanel(Genre genre) {
        initComponents();
        genreID.setText(genre.getGenreID());
        mgID.setText(genre.getMainGenreID());
        cover.setText(genre.getImagePath());
        genrename.setText(genre.getGenreName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genreID = new javax.swing.JLabel();
        genrename = new javax.swing.JLabel();
        mgID = new javax.swing.JLabel();
        cover = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genreID.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        genreID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genreID.setText("Genre ID");
        add(genreID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 90));

        genrename.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        genrename.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genrename.setText("Genre Name");
        add(genrename, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, 90));

        mgID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mgID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mgID.setText("MainGenre ID");
        add(mgID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 120, 90));

        cover.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cover.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cover.setText("Image Cover");
        add(cover, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 370, 90));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cover;
    private javax.swing.JLabel genreID;
    private javax.swing.JLabel genrename;
    private javax.swing.JLabel mgID;
    // End of variables declaration//GEN-END:variables
}
