/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import Classes.Transaction;
import java.text.SimpleDateFormat;

/**
 *
 * @author Aesthetics
 */
public class TransactionPanel extends javax.swing.JPanel {

    String formattedDate;
    SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy");

    public TransactionPanel(Transaction transaction) {
        initComponents();
        id.setText(transaction.getTransactionID());
        userID.setText(transaction.getUserID());
        method.setText(transaction.getPaymentMethod());
        formattedDate = dateFormat.format(transaction.getTransactionDate());
        date.setText(formattedDate);
        pay.setText("Php " + Double.toString(transaction.getAmountToPay()) + "0");
        paid.setText("Php " + Double.toString(transaction.getAmountToPay()) + "0");
        status.setText(transaction.getTransactionStatus());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        userID = new javax.swing.JLabel();
        method = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        paid = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        id.setText("Transaction ID");
        header.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 80));

        date.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        date.setText("Transaction Date");
        header.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 140, 80));

        status.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        status.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        status.setText("Status");
        header.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 110, 80));

        userID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        userID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userID.setText("User ID");
        header.add(userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 70, 80));

        method.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        method.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        method.setText("Method");
        header.add(method, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 80, 80));

        pay.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        pay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pay.setText("Amount To Pay");
        header.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 130, 80));

        paid.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        paid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        paid.setText("Amount Paid");
        header.add(paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 130, 80));

        add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JPanel header;
    private javax.swing.JLabel id;
    private javax.swing.JLabel method;
    private javax.swing.JLabel paid;
    private javax.swing.JLabel pay;
    private javax.swing.JLabel status;
    private javax.swing.JLabel userID;
    // End of variables declaration//GEN-END:variables
}
